### PR TITLE
Fix: Harden the transfer flow for unexpected data

### LINKED ISSUE #1566: librespot Invalid state { the provided context has no tracks }
### Description
librespot starts OK but when trying to connect to it from another device, the connection fails and librespot reports the error message:
librespot[2292]: [2025-09-03T12:54:43Z ERROR librespot_connect::spirc] failed to handle request: Invalid state { the provided context has no tracks }

### Version
librespot 0.6.0-dev ba3d501 (Built on 2025-08-11, Build ID: tEs7vh4i, Profile: release)

### How to reproduce
Steps to reproduce the behavior in *librespot* 
1. Launch `librespot` either from the the command line or automatically on boot, no errors at this point
2. Try to connect with Android Spotify app 
3.  The connection fails after a few seconds trying
4. Librespot on the Raspberry Pi reports the error above

### Log
```
$ librespot --verbose
[2025-09-03T13:16:01Z INFO  librespot] librespot 0.6.0-dev ba3d501 (Built on 2025-08-11, Build ID: tEs7vh4i, Profile: release)
[2025-09-03T13:16:01Z TRACE librespot] Command line argument(s):
[2025-09-03T13:16:01Z TRACE librespot] 		verbose
[2025-09-03T13:16:01Z DEBUG librespot_core::session] new Session
[2025-09-03T13:16:01Z DEBUG librespot_discovery::server] Zeroconf server listening on 0.0.0.0:43833
[2025-09-03T13:16:01Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2025-09-03T13:16:01Z DEBUG librespot_playback::player] new Player [0]
[2025-09-03T13:16:01Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2025-09-03T13:16:01Z INFO  librespot_playback::audio_backend::alsa] Using AlsaSink with format: S16
[2025-09-03T13:16:01Z DEBUG librespot_discovery] Pinged Avahi: Available
[2025-09-03T13:16:01Z TRACE librespot_discovery] Connected to Avahi
[2025-09-03T13:16:01Z DEBUG librespot_discovery] Commited zeroconf service with name librespot
[2025-09-03T13:16:02Z INFO  librespot_discovery] Published zeroconf service
[2025-09-03T13:16:12Z DEBUG librespot_discovery::server] POST "/" {}
[2025-09-03T13:16:12Z DEBUG librespot_core::session] Shutdown: Invalidating session
[2025-09-03T13:16:12Z DEBUG librespot::component] new MercuryManager
[2025-09-03T13:16:12Z DEBUG librespot::component] new ChannelManager
[2025-09-03T13:16:12Z DEBUG librespot_core::session] new Session
[2025-09-03T13:16:12Z DEBUG librespot_connect::spirc] new Spirc[0]
[2025-09-03T13:16:12Z DEBUG librespot_playback::player] command=SetSession
[2025-09-03T13:16:12Z DEBUG librespot::component] new DealerManager
[2025-09-03T13:16:12Z DEBUG librespot_core::session] drop Session
[2025-09-03T13:16:12Z DEBUG librespot::component] drop ChannelManager
[2025-09-03T13:16:12Z DEBUG librespot::component] drop MercuryManager
[2025-09-03T13:16:12Z DEBUG librespot::component] new SpClient
[2025-09-03T13:16:12Z DEBUG librespot_core::spclient] Client token unavailable or expired, requesting new token.
[2025-09-03T13:16:12Z DEBUG librespot_core::http_client] Requesting https://clienttoken.spotify.com/v1/clienttoken
[2025-09-03T13:16:12Z DEBUG librespot_core::spclient] Received a granted token
[2025-09-03T13:16:12Z TRACE librespot_core::spclient] Got client token: GrantedTokenResponse { token: "AAAq6BJT63ObpDdHMJ6QwaWPCCSHM9tXZutfRWIalNU71ArtrHZ3yVSZQqBBt402Rl3pwy0kpGScNqfiFHx/VHOXhcTeX4FdAnw2kfh76v1s6fVKIE973gXt+e/dZ/erlu2Qc6DghYB0Snpavck0yPm9HX8gKA1BsYR7VqKcVtu7FqcVHciecXHS1w77qQ4Cu1p2XIvvBbfHOihjpKg02UzABPhup1NOeTWhKpvuw/lG2bpavGtnste/abWLEuSMEjZotE+ylKOjF+xDlM6mHKJ0iR/AcHlxfbPEyRld2A==", expires_after_seconds: 1216800, refresh_after_seconds: 1209600, domains: [TokenDomain { domain: "spotify.com", special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }, TokenDomain { domain: "spotify.net", special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }], special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[2025-09-03T13:16:12Z DEBUG librespot::component] new ApResolver
[2025-09-03T13:16:12Z DEBUG librespot_core::http_client] Requesting https://apresolve.spotify.com/?type=accesspoint&type=dealer&type=spclient
[2025-09-03T13:16:12Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:4070"
[2025-09-03T13:16:12Z DEBUG librespot_core::connection] Connection to AP established.
[2025-09-03T13:16:12Z DEBUG librespot_core::connection] Authenticating with AP using AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS
[2025-09-03T13:16:12Z INFO  librespot_core::session] Authenticated as 'postman2' !
[2025-09-03T13:16:12Z DEBUG librespot::component] new Login5Manager
[2025-09-03T13:16:12Z DEBUG librespot_core::http_client] Requesting https://login5.spotify.com/v3/login
[2025-09-03T13:16:12Z TRACE librespot_core::session] Received Ping
[2025-09-03T13:16:12Z TRACE librespot_core::session] keep-alive state: PendingPong, timeout in 60.0
[2025-09-03T13:16:12Z DEBUG librespot_core::session] Session strong=5 weak=6
[2025-09-03T13:16:12Z INFO  librespot_core::session] Country: "GB"
[2025-09-03T13:16:12Z TRACE librespot_core::session] Received product info: {
        "image-url": "https://i.scdn.co/image/{file_id}",
        "public-toplist": "7",
        "name": "Spotify Premium",
        "ad-session-persistence": "1",
        "explicit-content": "1",
        "key-caching-max-count": "10000",
        "prefetch-keys": "1",
        "active-session-days": "16",
        "mobile": "1",
        "audiobook-onboarding-completed": "0",
        "user-profile-show-invitation-codes": "0",
        "prefetch-strategy": "18",
        "unrestricted": "1",
        "video-keyframe-url": "http://keyframes-fa.cdn.spotify.com/keyframes/v1/sources/{source_id}/keyframe/heights/{height}/timestamps/{timestamp_ms}.jpg",
        "ab-ad-player-targeting": "1",
        "audio-preview-url-template": "https://p.scdn.co/mp3-preview/{id}",
        "shuffle": "0",
        "payments-locked-state": "0",
        "nft-disabled": "1",
        "app-developer": "0",
        "employee-free-opt-in": "0",
        "streaming": "1",
        "metadata-link-lookup-modes": "0",
        "player-license-v2": "premium",
        "collection": "1",
        "payments-initial-campaign": "default",
        "publish-playlist": "1",
        "preferred-locale": "en",
        "ad-formats-preroll-video": "0",
        "head-file-caching": "1",
        "capping-bar-threshold": "3601",
        "is_email_verified": "1",
        "head-files-url": "http://heads-fa.spotify.com/head/{file_id}",
        "arsenal_country": "1",
        "widevine-license-url": "https://spclient.wg.spotify.com/widevine-license/v1/video/license",
        "music-videos": "1",
        "shows-collection": "0",
        "network-operator-premium-activation": "1",
        "incognito_mode_timeout": "21600",
        "ugc-abuse-report-url": "https://support.spotify.com/abuse/?uri={uri}",
        "sidebar-navigation-enabled": "0",
        "shows-collection-jam": "0",
        "video-manifest-url": "https://spclient.wg.spotify.com/manifests/v6/{type}/sources/{source_id}",
        "video-device-blacklisted": "0",
        "on-demand-trial-in-progress": "0",
        "libspotify": "1",
        "playlist-annotations-markup": "0",
        "financial-product": "pr:premium,tc:0,rt:v2_GB_default_individual-basic-1m-1m_10.99_GBP_default",
        "prefetch-window-max": "2",
        "send-email": "1",
        "enable-annotations-read": "0",
        "storage-size-config": "10240,90,500,3",
        "key-caching-max-offline-seconds": "1800",
        "restrict-playlist-collaboration": "0",
        "player-license": "premium",
        "ab-watch-now": "0",
        "publish-activity": "0",
        "ugc-abuse-report": "0",
        "catalogue": "premium",
        "ads": "0",
        "browse-overview-enabled": "1",
        "type": "premium",
        "on-demand": "1",
        "remote-control": "0",
        "license-acceptance-grace-days": "30",
        "ab_recently_played_feature_time_filter_threshold": "com.spotify.gaia=30,driving-mode=120,spotify%3Ainternal%3Astartpage=30",
        "high-bitrate": "1",
        "offline": "1",
        "enable-crossfade": "1",
        "filter-explicit-content": "0",
        "video-cdn-sampling": "100",
        "radio": "1",
        "mobile-payment": "0",
        "head-files": "1",
    }
[2025-09-03T13:16:12Z DEBUG librespot::component] new MercuryManager
[2025-09-03T13:16:12Z TRACE librespot_core::mercury] mercury response <hm://pusher/v1/connections/N2MyOGFiOGE1Yzk1MTJlNDI2NmFjN2NiNzU2MzEyYzgyZWU0M2Q3ZStBUCt0Y3A6Ly8wYWNhNDA2Ni5pcC5nZXcxLnNwb3RpZnkubmV0OjUwMTMrMTRFRTcxMDczOEJBOUVCQjgxRDZEOEZCNjUyNjkzNzdENjFEMUM4M0UwQUMzNkEyNjNCOTgzNDQ4OUNEMTk0Nw%3D%3D> is handled by dealer
[2025-09-03T13:16:12Z TRACE librespot_core::login5] Got auth token: Token { access_token: "BQBMozJZEUXvEXPnVoPPMKpq1XuseKdTCsEjDCpxPC5nIPHOkEp8K6qwZ_TyqFgLtajFhnN4lIb-5Ph2Yt-KWBn87k76YNoC3tIhM19GDKc73o3Pg7funkpTZ8XkL95oWsp8scZWc9mIjTN-ef15aMFVMlaW23Qerur48IM4HK_851t77HepFVVLpQ2UmLL2FYxwrZ9z8Jj1bi6bpvLSEfp81bPkMNg2tpfl8gPhYZUkShSgg0GNPOxDeLfsaONKJ0SsEmWz8ZUVkxvFRqI5dzv8fb3zOd0jT1Kc4QAnrrcsC4xtvYpAMx4k2PvQKLjX_dwqMDPIt22ERkk5ai_FC9XgFZBi1vbTzRfYnMb2LLNa1_lVGoT9L0Icx1ppuWjeCfD_c09SX_k", expires_in: 3600s, token_type: "Bearer", scopes: [], timestamp: Instant { tv_sec: 15154, tv_nsec: 454289944 } }
[2025-09-03T13:16:12Z DEBUG librespot_connect::spirc] SpircTask::set_volume(0)
[2025-09-03T13:16:12Z DEBUG librespot_playback::player] command=AddEventSender
[2025-09-03T13:16:12Z DEBUG librespot_core::dealer::manager] Launching dealer
[2025-09-03T13:16:12Z TRACE librespot_core::dealer] Sent ping
[2025-09-03T13:16:12Z TRACE librespot_connect::spirc] Received connection ID update: "YjU1MmQ1YjMtNGM2My00OTcxLWE2ZDYtMTVmOGIwZDM5Y2RhK2RlYWxlcit0Y3A6Ly8wYWNhNDE3Mi5pcC5nZXcxLnNwb3RpZnkubmV0OjU3MDArODc4MUNGRDExOEY5OThCNzMwMjc0Mzc3OTc3MzA4MjNFRUY0NTI0QTUyRDkwQzNENTk5NzAyNzZBMTRCOUY1Rg=="
[2025-09-03T13:16:12Z INFO  librespot_core::spclient] Resolved "gew1-spclient.spotify.com:443" as spclient access point
[2025-09-03T13:16:12Z DEBUG librespot_core::http_client] Requesting https://gew1-spclient.spotify.com:443/connect-state/v1/devices/7c28ab8a5c9512e4266ac7cb756312c82ee43d7e?product=0&country=GB&salt=2829884176
[2025-09-03T13:16:12Z TRACE librespot_core::dealer] Received pong
[2025-09-03T13:16:12Z DEBUG librespot_connect::spirc] successfully put connect state for 7c28ab8a5c9512e4266ac7cb756312c82ee43d7e with connection-id YjU1MmQ1YjMtNGM2My00OTcxLWE2ZDYtMTVmOGIwZDM5Y2RhK2RlYWxlcit0Y3A6Ly8wYWNhNDE3Mi5pcC5nZXcxLnNwb3RpZnkubmV0OjU3MDArODc4MUNGRDExOEY5OThCNzMwMjc0Mzc3OTc3MzA4MjNFRUY0NTI0QTUyRDkwQzNENTk5NzAyNzZBMTRCOUY1Rg==
[2025-09-03T13:16:12Z INFO  librespot_connect::spirc] active device is <> with session <1PiJmgME1g2Tbnj7rOaCdt>
[2025-09-03T13:16:12Z TRACE librespot_core::dealer] dealer request hm://connect-state/v1/player/command
[2025-09-03T13:16:12Z TRACE librespot_core::dealer::protocol] message was sent with gzip encoding 
[2025-09-03T13:16:12Z TRACE librespot_core::dealer::protocol] websocket request: Object {
        "command": Object {
            "data": String("ChwIABAAGAAqCQoFbWVkaWESACoJCgVtZWRpYRIAEpQFCIroz/mQMxAAGQAAAAAAAAAAIAEq/QQKABIgMjUwMTY3ZTFkMjkwNDBmNjhmOGYzYmY3MjkyZGUxNjcaEAc8whYmj0GfohNhRNILsN8iMwoKYXJ0aXN0X3VyaRIlc3BvdGlmeTphcnRpc3Q6NHRad2ZnckhPYzNtdnFZbEVZU3ZWaSIgCgV0aXRsZRIXR2l2ZSBMaWZlIEJhY2sgdG8gTXVzaWMiSQoPaW1hZ2VfbGFyZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMGIyNzM5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciKgogYWN0aW9ucy5za2lwcGluZ19wcmV2X3Bhc3RfdHJhY2sSBnJlc3VtZSJKChBpbWFnZV94bGFyZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMGIyNzM5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciQwoJaW1hZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMDFlMDI5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciMQoJYWxidW1fdXJpEiRzcG90aWZ5OmFsYnVtOjRtMjg4MGppdlNiYnlFR0FLZklUQ2EiSQoPaW1hZ2Vfc21hbGxfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMDQ4NTE5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciJQoLYWxidW1fdGl0bGUSFlJhbmRvbSBBY2Nlc3MgTWVtb3JpZXMiFQoMdHJhY2tfcGxheWVyEgVhdWRpbyIqCiBhY3Rpb25zLnNraXBwaW5nX25leHRfcGFzdF90cmFjaxIGcmVzdW1lGvgDCnoKCHBsYXlsaXN0Eit3ZWItcGxheWVyXzIwMjUtMDktMDJfMTc1NjgwNDM0NzU5M181ZTZhZTQyGgAiACoIZGVlcGxpbmsyKDg4YjA5OWRjNTA5YmYxNDVjNDFlM2NhZWE4ODBmNmI1ODIwNTVjN2I6B2Nvbm5lY3RCABK5AgoBLRIKY29udGV4dDovLxoZChBlbmhhbmNlZF9jb250ZXh0EgVmYWxzZRogChtwbGF5bGlzdF9udW1iZXJfb2ZfZXBpc29kZXMSATAaHwoZcGxheWxpc3RfbnVtYmVyX29mX3RyYWNrcxICMTMaGQoNY29udGV4dF9vd25lchIIcG9zdG1hbjIaEgoObG9hZGluZy5mYWlsZWQSABo2ChxwbGF5bGlzdF92b2xhdGlsZV9jb250ZXh0X2lkEhYyVVQ5VVdwcmdNb09WZldWSkU2bDRBGhUKDmxvYWRpbmcuc3RhdHVzEgM0MDQaDQoJaW1hZ2VfdXJsEgAaOQoTY29udGV4dF9kZXNjcmlwdGlvbhIiRGFmdCBQdW5rIC0gUmFuZG9tIEFjY2VzcyBNZW1vcmllcyIAMAEaIDI1MDE2N2UxZDI5MDQwZjY4ZjhmM2JmNzI5MmRlMTY3IgAqADIAShY2ZktTUG96RFhySktrRm9tb3NvYTdLIgIQADoCCgA="),
            "endpoint": String("transfer"),
            "from_device_identifier": String("88b099dc509bf145c41e3caea880f6b582055c7b"),
            "logging_params": Object {
                "command_id": String("d9d99a4a1afd47b08f9868a74c03bf7d"),
                "interaction_ids": Array [
                    String("dea54008-f5b3-4730-9c98-72470823cdba"),
                ],
            },
            "options": Object {
                "license": String("premium"),
                "restore_paused": String("restore"),
                "restore_position": String("extrapolate"),
                "restore_track": String("always_play_something"),
                "retain_session": String("do_not_retain"),
            },
        },
        "message_id": Number(263749628),
        "play_on_secondary_stream": Null,
        "sent_by_device_id": String("88b099dc509bf145c41e3caea880f6b582055c7b"),
        "target_alias_id": Null,
    }
[2025-09-03T13:16:12Z DEBUG librespot_connect::spirc] handling: 'endpoint: transfer' from 88b099dc509bf145c41e3caea880f6b582055c7b
[2025-09-03T13:16:12Z DEBUG librespot_connect::state::context] context didn't change, no reset
[2025-09-03T13:16:12Z WARN  librespot_connect::state::context] couldn't load context info because: context is not available. type: Default
[2025-09-03T13:16:12Z DEBUG librespot_connect::spirc] found initial track <spotify:track:0dEIca2nhcxDUV8C5QkPYb>
[2025-09-03T13:16:12Z ERROR librespot_connect::state::context] context didn't have any tracks: Context {
        uri: None,
        url: None,
        metadata: {},
        restrictions: MessageField(
            None,
        ),
        pages: [
            ContextPage {
                page_url: None,
                next_page_url: None,
                metadata: {},
                tracks: [],
                loading: None,
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        loading: None,
        special_fields: SpecialFields {
            unknown_fields: UnknownFields {
                fields: None,
            },
            cached_size: CachedSize {
                size: 0,
            },
        },
    }
[2025-09-03T13:16:12Z ERROR librespot_connect::spirc] failed to handle request: Invalid state { the provided context has no tracks }
[2025-09-03T13:16:12Z DEBUG librespot_core::dealer::manager] replying to ws request: Failure
[2025-09-03T13:16:15Z TRACE librespot_core::dealer] dealer request hm://connect-state/v1/player/command
[2025-09-03T13:16:15Z TRACE librespot_core::dealer::protocol] message was sent with gzip encoding 
[2025-09-03T13:16:15Z TRACE librespot_core::dealer::protocol] websocket request: Object {
        "command": Object {
            "data": String("ChwIABAAGAAqCQoFbWVkaWESACoJCgVtZWRpYRIAEpQFCIroz/mQMxAAGQAAAAAAAAAAIAEq/QQKABIgMjUwMTY3ZTFkMjkwNDBmNjhmOGYzYmY3MjkyZGUxNjcaEAc8whYmj0GfohNhRNILsN8iMwoKYXJ0aXN0X3VyaRIlc3BvdGlmeTphcnRpc3Q6NHRad2ZnckhPYzNtdnFZbEVZU3ZWaSIgCgV0aXRsZRIXR2l2ZSBMaWZlIEJhY2sgdG8gTXVzaWMiSQoPaW1hZ2VfbGFyZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMGIyNzM5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciKgogYWN0aW9ucy5za2lwcGluZ19wcmV2X3Bhc3RfdHJhY2sSBnJlc3VtZSJKChBpbWFnZV94bGFyZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMGIyNzM5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciQwoJaW1hZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMDFlMDI5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciMQoJYWxidW1fdXJpEiRzcG90aWZ5OmFsYnVtOjRtMjg4MGppdlNiYnlFR0FLZklUQ2EiSQoPaW1hZ2Vfc21hbGxfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMDQ4NTE5YjliMzZiMGUyMjg3MGI5ZjU0MmQ5MzciJQoLYWxidW1fdGl0bGUSFlJhbmRvbSBBY2Nlc3MgTWVtb3JpZXMiFQoMdHJhY2tfcGxheWVyEgVhdWRpbyIqCiBhY3Rpb25zLnNraXBwaW5nX25leHRfcGFzdF90cmFjaxIGcmVzdW1lGvgDCnoKCHBsYXlsaXN0Eit3ZWItcGxheWVyXzIwMjUtMDktMDJfMTc1NjgwNDM0NzU5M181ZTZhZTQyGgAiACoIZGVlcGxpbmsyKDg4YjA5OWRjNTA5YmYxNDVjNDFlM2NhZWE4ODBmNmI1ODIwNTVjN2I6B2Nvbm5lY3RCABK5AgoBLRIKY29udGV4dDovLxoZChBlbmhhbmNlZF9jb250ZXh0EgVmYWxzZRogChtwbGF5bGlzdF9udW1iZXJfb2ZfZXBpc29kZXMSATAaHwoZcGxheWxpc3RfbnVtYmVyX29mX3RyYWNrcxICMTMaGQoNY29udGV4dF9vd25lchIIcG9zdG1hbjIaEgoObG9hZGluZy5mYWlsZWQSABo2ChxwbGF5bGlzdF92b2xhdGlsZV9jb250ZXh0X2lkEhYyVVQ5VVdwcmdNb09WZldWSkU2bDRBGhUKDmxvYWRpbmcuc3RhdHVzEgM0MDQaDQoJaW1hZ2VfdXJsEgAaOQoTY29udGV4dF9kZXNjcmlwdGlvbhIiRGFmdCBQdW5rIC0gUmFuZG9tIEFjY2VzcyBNZW1vcmllcyIAMAEaIDI1MDE2N2UxZDI5MDQwZjY4ZjhmM2JmNzI5MmRlMTY3IgAqADIAShY2ZktTUG96RFhySktrRm9tb3NvYTdLIgIQADoCCgA="),
            "endpoint": String("transfer"),
            "from_device_identifier": String("88b099dc509bf145c41e3caea880f6b582055c7b"),
            "logging_params": Object {
                "command_id": String("d9d99a4a1afd47b08f9868a74c03bf7d"),
                "interaction_ids": Array [
                    String("dea54008-f5b3-4730-9c98-72470823cdba"),
                ],
            },
            "options": Object {
                "license": String("premium"),
                "restore_paused": String("restore"),
                "restore_position": String("extrapolate"),
                "restore_track": String("always_play_something"),
                "retain_session": String("do_not_retain"),
            },
        },
        "message_id": Number(263752711),
        "play_on_secondary_stream": Null,
        "sent_by_device_id": String("88b099dc509bf145c41e3caea880f6b582055c7b"),
        "target_alias_id": Null,
    }
[2025-09-03T13:16:15Z DEBUG librespot_connect::spirc] handling: 'endpoint: transfer' from 88b099dc509bf145c41e3caea880f6b582055c7b
[2025-09-03T13:16:15Z DEBUG librespot_connect::state::context] context didn't change, no reset
[2025-09-03T13:16:15Z WARN  librespot_connect::state::context] couldn't load context info because: context is not available. type: Default
[2025-09-03T13:16:15Z DEBUG librespot_connect::spirc] found initial track <spotify:track:0dEIca2nhcxDUV8C5QkPYb>
[2025-09-03T13:16:15Z ERROR librespot_connect::state::context] context didn't have any tracks: Context {
        uri: None,
        url: None,
        metadata: {},
        restrictions: MessageField(
            None,
        ),
        pages: [
            ContextPage {
                page_url: None,
                next_page_url: None,
                metadata: {},
                tracks: [],
                loading: None,
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        loading: None,
        special_fields: SpecialFields {
            unknown_fields: UnknownFields {
                fields: None,
            },
            cached_size: CachedSize {
                size: 0,
            },
        },
    }
[2025-09-03T13:16:15Z ERROR librespot_connect::spirc] failed to handle request: Invalid state { the provided context has no tracks }
[2025-09-03T13:16:15Z DEBUG librespot_core::dealer::manager] replying to ws request: Failure
[2025-09-03T13:16:42Z TRACE librespot_core::dealer] Sent ping
[2025-09-03T13:16:42Z TRACE librespot_core::dealer] Received pong
```

### Host (what you are running `librespot` on):
- OS: Linux
- Platform: RPi 5 
- Linux raspberrypi 6.12.34+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.12.34-1+rpt1~bookworm (2025-06-26) aarch64

### Additional context
I am seeing the same error on a Mycroft Mark 2 running NeonOS which includes librespot

### PR DESCRIPTION
**Pull request by photovoltex**
Fixes the transfer flow handling when the `context_uri` is empty and the context has no tracks. I'm still not sure how this can happen, but some users seem to have encountered it so this should improve the handling for these specific cases.

Additionally the grayed out play/pause button when transferring was fixed and should now stay enabled during transfering.

Fixes #1566

### CODE REVIEW

File: connect/src/spirc.rs [hunk 1]
```diff
@@ -1148,11 +1153,18 @@ impl SpircTask {
         if load_from_context_uri {
             self.transfer_state = Some(transfer);
         } else {
-            let ctx = self.connect_state.get_context(ContextType::Default)?;
-            let idx = ConnectState::find_index_in_context(ctx, |pt| {
-                self.connect_state.current_track(|t| pt.uri == t.uri)
-            })?;
-            self.connect_state.reset_playback_to_position(Some(idx))?;
+            match self.connect_state.get_context(ContextType::Default) {
+                Err(_) => {
```
Comment (roderickvd) [inline connect/src/spirc.rs]: Would it be helpful to capture the error?

```rust
Err(e) => {
    warn!("no context to reset with: {e}, continuing transfer after context resolved"),
    // ..
}
```

File: connect/src/state/transfer.rs [hunk 2]
```diff
@@ -84,8 +86,8 @@ impl ConnectState {
             }
         }
 
-        player.context_url.clear();
-        player.context_uri.clear();
+        player.context_url = format!("context://{ctx_uri}");
```
Comment (roderickvd) [inline connect/src/state/transfer.rs]: Do we need to check for an empty or otherwise malformed `ctx_uri` here?

**Review by roderickvd — COMMENTED** [review]
Also minor questions. Sorry for the long wait for the review!

File: connect/src/spirc.rs (hunk 1 above)
Comment (photovoltex) [reply connect/src/spirc.rs]: I thought dropping the error and providing a different message that explains it would be enough, but it's probably better to just let the error speak and add some more details to it.

File: connect/src/state/transfer.rs (hunk 2 above)
Comment (photovoltex) [reply connect/src/state/transfer.rs]: I updated the handling a bit and an empty string or `-` are now handled separately.

File: connect/src/spirc.rs [hunk 3]
```diff
@@ -1369,6 +1374,9 @@ impl SpircTask {
 
     fn load_context_from_tracks(&mut self, tracks: impl Into<ContextPage>) -> Result<(), Error> {
         let ctx = Context {
+            // by providing values for uri/url the player in the official client's isn't frozen
+            uri: Some(String::from("spotify:web-api")),
+            url: Some(String::from("context://spotify:web-api")),
```
Comment (roderickvd) [inline connect/src/spirc.rs]: Small nitpick: for maintainability you could use `format!("context://{uri}")` here.

File: connect/src/state/transfer.rs [hunk 4]
```diff
@@ -86,8 +90,14 @@ impl ConnectState {
...
 
-        player.context_url = format!("context://{ctx_uri}");
-        player.context_uri = ctx_uri;
+        if let Some(ctx_uri) = ctx_uri {
+            player.context_url = format!("context://{ctx_uri}");
+            player.context_uri = ctx_uri;
+        } else {
+            // it's important to always set the url/uri to a value so that the player is active
+            player.context_url = String::from("context://spotify:unknown");
+            player.context_uri = String::from("spotify:unknown");
```
Comment (roderickvd) [inline connect/src/state/transfer.rs]: Same.

**Review by roderickvd — DISMISSED** [review]
LGTM
