### PR TITLE
Fix spotify version in client token request

### LINKED ISSUE #1281: regression: lyrics API no longer working
Trying to fetch lyrics is now failing with:

`Client specified an invalid argument { Response status code: 400 Bad Request }`

I bissected it and this regression has been introduced by d881f46ce744da452417d513f35dd0d070c16509 from @acolombier 

(Note that you also need https://github.com/librespot-org/librespot/pull/1280 to get lyrics working but it's unrelated to this problem).

### PR DESCRIPTION
**Pull request by DaXcess**
Fixes #1281

### CODE REVIEW

File: core/src/version.rs [hunk 1]
```diff
@@ -29,6 +29,13 @@ pub const SPOTIFY_MOBILE_VERSION: &str = "8.6.84";
...
 pub fn spotify_version() -> String {
+    match std::env::consts::OS {
+        "android" | "ios" => SPOTIFY_MOBILE_VERSION.to_owned(),
+        _ => SPOTIFY_VERSION.to_string(),
+    }
+}
+
+pub fn spotify_semantic_version() -> String {
     match std::env::consts::OS {
         "android" | "ios" => SPOTIFY_MOBILE_VERSION.to_owned(),
```
Comment (DaXcess) [inline core/src/version.rs:40]: I'm not entirely sure which version notation mobile uses, as I currently am not easily able to intercept Spotify communication on mobile. For now I've kept the behavior the same as before d881f46ce744da452417d513f35dd0d070c16509.

**Comment by roderickvd** [comment]
Thanks!
