### PR TITLE
Spirc: Replace Mecury with Dealer 

### LINKED ISSUE #19: Shuffle/Repeat buttons are not fully functional.
Good to see you guys keep this project alive!

Basically copy/paste from [plietar's repo issue #82](https://github.com/plietar/librespot/issues/82)

### LINKED ISSUE #434: Wrong behaviour after finishing a playlist/album
Official Spotify Clients jump to the first song in the playlist/album after playing the last one.

Librespot jumps 10 songs back when the playlist is over.
For example if the last song in an album is 26, librespot will jump to song number 16 when the last song is over.
If the album has 11 or less songs, it goes to the first, which is correct.

This issue would be minor, but this breaks looping any album/list longer than 11 songs.

### LINKED ISSUE #442: Only subsection of large playlist gets played in spotify connect
Hi -

I am experiencing an issue where all the songs in a playlist cannot be played through the connect feature. It looks to me like only 80 songs get sent to the play queue, and the queue does not get sent any 'new' songs. When the end of the queue is reached, the initial 80 songs that were sent to the queue are then played again.

[2020-03-03T01:42:06Z INFO  librespot] librespot  (). Built on 2020-03-02. Build ID: a527MUNO

Expected behavior (casting to Spotify app on Android TV)
https://imgur.com/mX7CePc

Observed behavior (casting to librespot client on a raspberry pi)
https://imgur.com/a/zMnasMu

Thanks and let me know what additional info would be helpful.

### LINKED ISSUE #701: Can't select multiple tracks in queue
Holding shift on the queue screen allows you to select multiple items. When streaming to librespot this functionality stops working. ( [video](https://d.tdrz.nl/FGovWnR6.webm) )

I still have an older version of the desktop client on my Linux machine where it works fine so I suspect something changed after the new UI update that broke this.

I recently posted an issue to the Spotify community thinking it was an issue on their side 
however I can't seem to reproduce this when streaming to other connect devices, such as my TV.
( https://community.spotify.com/t5/Desktop-Windows/Can-t-select-multiple-items-in-queue-when-using-Connect/m-p/5189816#M98391 )

### LINKED ISSUE #765: Playing from artist often causes a crash
I'm trying to play music from an artist, for example by doing a call to the Web API using `me/player/play` with `spotify:artist:70BYFdaZbEKbeauJ670ysI`, although, any artist seem to cause issues. A couple of tracks usually play fine, but after a short while, librespot seems to crash pretty consistently with a similar error message each time:
```
thread 'main' panicked at 'attempt to subtract with overflow', core/src/spotify_id.rs:121:20
```
Only happens when playing from any artist, anything else seems to work just fine. Playing from artist works poorly in general, as it only seems to play a few tracks, maybe related?

[stack_backtrace.log](https://github.com/librespot-org/librespot/files/6552791/stack_backtrace.log)

### LINKED ISSUE #861: Play Queue inconsistencies with Android and librespot.
Hello good people,

I have come over from the community at the moOde Forum to report some behaviour we have spotted when using the Spotify Android app in conjunction with librespot.  The discussion relating to this can be read here: https://moodeaudio.org/forum/showthread.php?tid=4215 (some useful screenshots at post 10).

To reproduce the issue, first start playing a playlist (or album) by playing the first item in the playlist, this should start playing and then add the subsequent tracks into the queue as "next from".
Now connect the session to librespot (in our case via moOde) and browse to the play queue using the Android app, you will find all the "next from" items are inert.
Connect to the same session using a different Spotify client (the Spotify Web Player for example) and browse to the play queue, those same "next from" items can be interacted with.
Finally disconnect from librespot, or connect to another connect device and notice that the items are no longer inert even on the Android app.

### LINKED ISSUE #1205: Autoplay is not working
**Describe the bug**
When using librespot with the described command, autoplay doesn't work: Either the same song gets repeated over and over again or the last selected radio/playlist/album gets played instead.

**To reproduce**
1. Use the following command to start librespot: `librespot --disable-audio-cache -n "mycroft-librespot" -b 320 --mixer alsa --enable-volume-normalisation --autoplay on --volume-ctrl linear --verbose`. I also tried this command with the same result: `librespot --disable-audio-cache -n "mycroft-librespot" -b 320 --mixer alsa --enable-volume-normalisation --autoplay --volume-ctrl linear --verbose`.
2. Connect with the device in the (Android) spotify app
3. In the app, play a song.
4. Try to press the "Next" button, the song will repeat.
5. If you previously played a radio over librespot, this radio will play, even if the selected song is entirely different from the radio.

**Log**
<details>

<summary>Log</summary>

```
[2023-09-25T20:29:34Z INFO  librespot] librespot 0.4.2 UNKNOWN (Built on 2023-09-25, Build ID: wdnG81uE, Profile: release)
[2023-09-25T20:29:34Z TRACE librespot] Command line argument(s):
[2023-09-25T20:29:34Z TRACE librespot]          disable-audio-cache
[2023-09-25T20:29:34Z TRACE librespot]          n "mycroft-librespot"
[2023-09-25T20:29:34Z TRACE librespot]          b "320"
[2023-09-25T20:29:34Z TRACE librespot]          mixer "alsa"
[2023-09-25T20:29:34Z TRACE librespot]          enable-volume-normalisation
[2023-09-25T20:29:34Z TRACE librespot]          autoplay
[2023-09-25T20:29:34Z TRACE librespot]          volume-ctrl "linear"
[2023-09-25T20:29:34Z TRACE librespot]          verbose
[2023-09-25T20:29:34Z WARN  librespot] Alsa specific options have no effect if the alsa backend is not enabled at build time.
[2023-09-25T20:29:34Z DEBUG librespot_discovery::server] Zeroconf server listening on 0.0.0.0:46221
[2023-09-25T20:29:55Z DEBUG librespot_discovery::server] POST "/" {}
[2023-09-25T20:29:55Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:4070
[2023-09-25T20:29:55Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:443
[2023-09-25T20:29:55Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
[2023-09-25T20:29:55Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2023-09-25T20:29:55Z INFO  librespot_core::session] Authenticated as "87zak4din53ffbyaelpp59uia" !
[2023-09-25T20:29:55Z DEBUG librespot_core::session] new Session[0]
[2023-09-25T20:29:55Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Linear
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] Normalisation Type: Auto
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] Normalisation Pregain: 0.0 dB
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] Normalisation Threshold: -2.0 dBFS
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] Normalisation Method: Dynamic
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] Normalisation Attack: 5 ms
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] Normalisation Release: 100 ms
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] Normalisation Knee: 5 dB
[2023-09-25T20:29:55Z DEBUG librespot_connect::spirc] new Spirc[0]
[2023-09-25T20:29:55Z DEBUG librespot_connect::spirc] canonical_username: 87zak4din53ffbyaelpp59uia
[2023-09-25T20:29:55Z DEBUG librespot::component] new MercuryManager
[2023-09-25T20:29:55Z DEBUG librespot_playback::mixer::mappings] Input volume 32767 mapped to: 50.00%
[2023-09-25T20:29:55Z DEBUG librespot_core::session] Session[0] strong=3 weak=2
[2023-09-25T20:29:55Z INFO  librespot_core::session] Country: "DE"
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] new Player[0]
[2023-09-25T20:29:55Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2023-09-25T20:29:55Z INFO  librespot_playback::audio_backend::rodio] Using Rodio sink with format S16 and cpal host: ALSA
[2023-09-25T20:29:55Z INFO  librespot_playback::audio_backend::rodio] Using audio device: default
[2023-09-25T20:29:55Z DEBUG librespot_playback::audio_backend::rodio] Rodio sink was created
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] command=AddEventSender
[2023-09-25T20:29:55Z DEBUG librespot_playback::player] command=VolumeSet(32767)
[2023-09-25T20:29:56Z DEBUG librespot_core::mercury] subscribed uri=hm://remote/user/87zak4din53ffbyaelpp59uia/ count=0
[2023-09-25T20:29:56Z DEBUG librespot_connect::spirc] kMessageTypeNotify "23049PCD8G" e37645146993c8db2977307701543e3572845800 1309198469 1695673795952 kPlayStatusPlay
[2023-09-25T20:29:56Z DEBUG librespot_connect::spirc] kMessageTypeNotify "mycroft-spotifyd" 039f9248fdfc790f08a86cd90cb230bb734bc88c 1309198469 1695673795952 kPlayStatusStop
[2023-09-25T20:29:56Z DEBUG librespot_connect::spirc] kMessageTypeLoad "23049PCD8G" e37645146993c8db2977307701543e3572845800 1309198737 1695673792998 kPlayStatusPlay
[2023-09-25T20:29:56Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:search:i%20want%20to%20break" index: 0 position_ms: 5170 status: kPlayStatusPlay position_measured_at: 1695673796581 context_description: "" shuffle: false repeat: false playing_from_fallback: true row: 0 playing_track_index: 0 track {gid: "\357\3313\253x7O\033\273\027\307Ug\363k6"}
[2023-09-25T20:29:56Z DEBUG librespot_connect::spirc] Frame has 1 tracks
[2023-09-25T20:29:56Z INFO  librespot_connect::spirc] Fetching autoplay context uri
[2023-09-25T20:29:56Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2023-09-25T20:29:56Z DEBUG librespot_playback::player] command=SetAutoNormaliseAsAlbum(false)
[2023-09-25T20:29:56Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 318813267399007593070930267639173573430, audio_type: Track }, true, 5170)
[2023-09-25T20:29:56Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2023-09-25T20:29:56Z WARN  librespot_core::mercury] error 400 for uri hm://autoplay-enabled/query?uri=spotify:search:i%20want%20to%20break
[2023-09-25T20:29:56Z ERROR librespot_connect::spirc] AutoplayError: MercuryError
[2023-09-25T20:29:56Z INFO  librespot_playback::player] Loading <I Want To Break Free> with Spotify URI <spotify:track:7iAqvWLgZzXvH38lA06QZg>
[2023-09-25T20:29:56Z DEBUG librespot_audio::fetch] Downloading file e94f9894b92365637e1b7cb826473fa8e8b86f22
[2023-09-25T20:29:56Z DEBUG librespot::component] new ChannelManager
[2023-09-25T20:29:57Z DEBUG librespot::component] new AudioKeyManager
[2023-09-25T20:29:57Z DEBUG librespot_connect::spirc] kMessageTypeNotify "23049PCD8G" e37645146993c8db2977307701543e3572845800 1309199653 1695673797136 kPlayStatusStop
[2023-09-25T20:29:59Z INFO  librespot_playback::player] <I Want To Break Free> (223080 ms) loaded
[2023-09-25T20:29:59Z DEBUG librespot_playback::player] Normalisation Data: NormalisationData { track_gain_db: -6.312110900878906, track_peak: 1.0102968215942383, album_gain_db: -9.44301700592041, album_peak: 1.0522888898849487 }
[2023-09-25T20:29:59Z DEBUG librespot_playback::player] Calculated Normalisation Factor for Track: 48.35%
[2023-09-25T20:29:59Z TRACE librespot_playback::player] == Starting sink ==
[2023-09-25T20:29:59Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2023-09-25T20:29:59Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
[2023-09-25T20:29:59Z DEBUG librespot_audio::fetch] Stream waiting for download of file position 210780. Downloaded ranges: ([0, 16383][141424, 157811][176736, 210779][212052, 228439][282680, 299067][565200, 581583][1130232, 1146619][2260296, 2276683][4520428, 4536815][9040696, 9057079]). Pending ranges: ([210780, 212051][228440, 282679][299068, 432699])
[2023-09-25T20:29:59Z DEBUG librespot_audio::fetch] Read at postion 210780 completed. 1811 bytes returned, 1811 bytes were requested.
[2023-09-25T20:30:13Z DEBUG librespot_connect::spirc] kMessageTypeNext "23049PCD8G" e37645146993c8db2977307701543e3572845800 1309215959 1695673799319 kPlayStatusStop
[2023-09-25T20:30:13Z DEBUG librespot_connect::spirc] At track 2 of 1 <"spotify:search:i%20want%20to%20break"> update [true]
[2023-09-25T20:30:13Z DEBUG librespot_connect::spirc] Extending playlist <spotify:search:i%20want%20to%20break>
[2023-09-25T20:30:13Z WARN  librespot_connect::spirc] No context to update from!
[2023-09-25T20:30:13Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2023-09-25T20:30:13Z DEBUG librespot_playback::player] command=SetAutoNormaliseAsAlbum(false)
[2023-09-25T20:30:13Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 318813267399007593070930267639173573430, audio_type: Track }, true, 0)
[2023-09-25T20:30:13Z DEBUG librespot_playback::player] Normalisation Data: NormalisationData { track_gain_db: -6.312110900878906, track_peak: 1.0102968215942383, album_gain_db: -9.44301700592041, album_peak: 1.0522888898849487 }
[2023-09-25T20:30:13Z DEBUG librespot_playback::player] Calculated Normalisation Factor for Track: 48.35%
[2023-09-25T20:30:13Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2023-09-25T20:30:13Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
[2023-09-25T20:30:13Z DEBUG librespot_audio::fetch] Stream waiting for download of file position 16384. Downloaded ranges: ([0, 16383][141424, 157811][176736, 3321163][4520428, 4536815][9040696, 9057079]). Pending ranges: ([16384, 141423][157812, 176735][3321164, 3341643])
[2023-09-25T20:30:13Z DEBUG librespot_audio::fetch] Read at postion 16384 completed. 1653 bytes returned, 1653 bytes were requested.
[2023-09-25T20:30:21Z DEBUG librespot_connect::spirc] kMessageTypePause "23049PCD8G" e37645146993c8db2977307701543e3572845800 1309223486 1695673813930 kPlayStatusPlay
[2023-09-25T20:30:21Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPause]
[2023-09-25T20:30:21Z DEBUG librespot_playback::player] command=Pause
[2023-09-25T20:30:21Z TRACE librespot_playback::player] == Stopping sink ==
[2023-09-25T20:30:21Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPause]
[2023-09-25T20:30:21Z TRACE librespot_connect::spirc] ==> kPlayStatusPause
^C[2023-09-25T20:30:25Z INFO  librespot] Gracefully shutting down
[2023-09-25T20:30:25Z DEBUG librespot_playback::player] command=Stop
[2023-09-25T20:30:26Z DEBUG librespot_connect::spirc] drop Spirc[0]
[2023-09-25T20:30:26Z DEBUG librespot_playback::player] Shutting down player thread ...
[2023-09-25T20:30:26Z DEBUG librespot_playback::player] drop PlayerInternal[0]
[2023-09-25T20:30:26Z DEBUG librespot_playback::player] PlayerInternal thread finished.
[2023-09-25T20:30:26Z DEBUG librespot_core::session] drop Session[0]
[2023-09-25T20:30:26Z DEBUG librespot::component] drop AudioKeyManager
[2023-09-25T20:30:26Z DEBUG librespot::component] drop ChannelManager
[2023-09-25T20:30:26Z DEBUG librespot::component] drop MercuryManager
[2023-09-25T20:30:26Z DEBUG librespot_core::session] drop Dispatch
```

</details>

**Host (what you are running `librespot` on):**
- OS: Raspberry PI OS 64bit
- Platform: RPi 4B 8GB

### LINKED ISSUE #1353: Can't jump to specific track in playlist
**Describe the bug**
I loaded up a playlist. Then I wanted to jump to the last track in the list to see how it would handle an "end of queue" event. I could click any track in the list, but it would only stop playback, not jump to that track.

**To reproduce**
1. `librespot -c . -name tescht --verbose &> test.log` (yes, I know, got the `name` parameter wrong, but anyway...)
2. Connect with Spotify for macOS (Apple Silicon) 1.2.45.454.gc16ec9f6
3. Play https://open.spotify.com/playlist/37i9dQZF1DZ06evO2UhT7X
4. Try to play a random track in the queue

**Log**
Too long to embed here, I guess. I'm not sure what the relevant part of it is: [test.log](https://github.com/user-attachments/files/17143674/test.log)

**Host (what you are running `librespot` on):**
- OS: macOS 14.6.1
- Platform: Mac14,9 (MacBook Pro M2 Pro, 14")
- `librespot 0.5.0-dev e02e4ae (Built on 2024-09-26, Build ID: 0kQU3dVK, Profile: debug)`

**Additional context**
The same interaction would work if playing from the application directly (not sending to `librespot`)

### PR DESCRIPTION
**Pull request by photovoltex**
<details><summary>Initial PR Description</summary>
<p>

As suggested from @roderickvd a draft PR so i can have some community feedback and give now and then updates on the progress.

The replacement is in a working state, so the very basic do work again. There is still a lot of cleanup and re-implementing to do.

But so far what is working:
- transferring the playback so that we are the player
  - funnily enough, transferring back isn't working yet
- play, pause, resume, prev, next, seek
- just general communication of our state to other clients

Previously Known Problems:
- [x] on the initial connection librespot doesn't appear, but if for example the volume is slightly updated, we should appear
  > this might be a web-player specific problem, in the client the dealer just pops up
  - this seems to be to some degree fine? if the devices are reopend it seems to be always there, it just isn't dynamically updated.
- [x] if the session or spirc/dealer dies, we lose our complete ConnectState
  - it would be nice if that is preserved so we could start from that again
- [x] sometimes other client's forget that we are the current player
  - ~might be that that is already resolved, but i think i still saw that behavior not so long ago~
  - update: seems to be resolved, was probably just an early development problem

What i still have to do:
- [x] handling the remaining request commands
  - [x] queue handling (set_queue, add_to_queue)
  - [x] repeat handling (set_repeating_track, set_repeating_context)
    - i didn't see these in the wild yet, so it might that they do not exists
  - [x] context handling (update_context)
  - [x] options handling (set_options)
    - should be related to shuffle and repeat
- [x] transferring the state to a different player again (stop playback if we are not active anymore)
- [x] resolving the context from a cold state
  - ~~currently it works really well if the playback starts from a different device like the web-player~~
  - ~~but from a cold start it's still a bit weird and not fully sorted out~~
  - we don't copy the player state from a running instance anymore, 
  - so that we actually use the the cold state resolving/handling/transfering
- [x] shuffling has to be re-implemented
  - we can set restrictions for the clients getting our state
  - so for autoplay we should ignore shuffeling and just disable repeat and shuffle
- [x] autoplay has to be fixed
- [x] i added the option for track repeat, but it's not handled yet
- [x] i would like to remove the remaining mercury calls
  - but for that i will have to see if the dealer sendes equivalent messages/requests

I tried to keep my code clean, but if there are points that i could improve and such, i would like to here them^^
</p>
</details> 

### Currently Known Issues:

- [x] podcasts/episodes don't work
   - see https://github.com/librespot-org/librespot/pull/1356#issuecomment-2512626032
- [x] starting a track out of "recent search" from mobile and then trying to switch back to mobile
   - see https://github.com/librespot-org/librespot/pull/1356#issuecomment-2509635805
   - seems to get into a weird state where the mobile app is completely desynced
- [ ] on mobile it can occur that librespot is seen as still playing with the current account, even tho it isn't playing
- [ ] shufflling a context with multiple pages does only shuffle the first page (because initially only that page is loaded)
   - this is a problem for example, when shuffling an artist context

Fixes #19 
- the dealer does support this via the field `repeating_track` and `set_options` command

Fixes #434 
- a context is now resolved completely

Fixes #442 
- a context is now resolved completely

Fixes #701 
- the dealer does support this action via the command `set_queue`

Fixes #765 
- resolve context does provide the top 10 tracks and all albums in order from newest to oldest 

Fixes #861 
- the next tracks are completely reworked

Fixes #1205 
- thx @PocketMiner82 for helping test :)

Fixes #1353 
- I encountered this issue during development, but after fixing everything around the uid's it seems to be fully functional now

Thx again to all people testing the branch, helps a lot :D

### CODE REVIEW

**Comment by photovoltex** [comment]
oh the branch might not compile because there are still some `todo!()` here and there which result in unreachable statements that clippy, understandably, doesn't like.

**Comment by roderickvd** [comment]
Super job! I know you're not there yet, so let's all contribute here. Stuff like this almost makes me sign up for a Spotify plan again :wink:

I'm gonna have a more thorough look later. Wanted to ping back on your comment over at #1349:

> The hm://pusher/v1/connections/<id> message is send after connecting to set up some connect stuff initially. Can be safely ignored as far as i know. It just falls under one of the many unknown subscriptions category that are logged.

If you look at `librespot-java`, you'll see that it listens to this message to extract the `Spotify-Connection-Id` from the headers:

https://github.com/librespot-org/librespot-java/blob/d0ff31b4f476590c9c17401aac01a6762e4ba908/player/src/main/java/xyz/gianlu/librespot/player/state/DeviceStateHandler.java#L162

I *think* if you follow the code flow, updating the connection ID then triggers the `ready` event in the `deviceStateListener`, which in turn gets the volume. And *that* seems to gel with you saying that:

> on the initial connection librespot doesn't appear, but if for example the volume is slightly updated, we should appear

**Comment by photovoltex** [comment]
I did recently go through old issues to see what this PR might fix. Following issues might we fix after merging these changes: 
- #19 
  - repeat track is an own state in the connect state context 
  - and i will probably adjust the repeat handling to behave like the web-player dealer
- #434, #442
  - this should also be fixed, but that's related to resolving the context and i currently push that back because it will require a bit more time to figure out how we want to resolve that correctly
- #676
  - sometimes i have the behavior that we don't disappear, but usually, when the web socket is closed we also disappear in the ui
  - might still have to investigate why we sometimes don't disappear tho
- #701, #861
  - i just implemented the `set_queue` command, which does exactly resolve this problem
  - `set_queue` is also used to remove all queued tracks from the queue
  - but for adding an item to the queue we receive the `add_to_queue` command

**Comment by roderickvd** [comment]
Thanks for sifting though the issue list. I agree, with this new infrastructure in place we'll stand a real chance of fixing those and perhaps more issues. A lot were related to stuff missing on spirc.

I said it before, but mega job man. This is going to be awesome.

**Comment by photovoltex** [comment]
So... if you don't use repeat, play unavailable tracks, or have any other edge cases, this should be a quite stable state, in terms of no hard bugs and crashes (except maybe an integer underflow that might happen if you request skip_prev too much).

The current collection handling is the same as in all playlist. But it seems like spotify handles the collection differently and the index of the current track seems to be always at 10... will see if i change that because that handling seems kinda unintuitive.

While testing i also still had some weird behaviors where i had offsets where there shouldn't be any. Did happen in my liked songs. where at around 5k i had an offset of 25, around 100 3 and at the beginning none. I think it might have to do something with unavailable songs... But technically we have all songs locally loaded as context... Will investigate that probably next time.

Next up will probably be repeat, a bit more stabilization and then autoplay. The might actually still work, but i would like to adjust them to the new logic, or at least test them and fix probelem^^;

**Comment by photovoltex** [comment]
Some updates for stability. Mostly reconnecting should now work (it actually doesn't reconnect, it just picks up the transfer-state that is given to use from the first connect-state update) and updating the volume now happens with a delay of 2 seconds. Additionally the context is back to being resolved asynchronously because for a smooth transfer it was a really bad idea to resolve the context synchronously.

There still seems to be some problems here and there. Sometimes completely losing our playback on the transfer (seems to be sporadic... yay) and a weird offset problem with the position of the track, or sometimes playing the prev track if the playback is transferred around the track transition.

File: connect/src/spirc.rs [hunk 1]
```diff
@@ -471,6 +421,68 @@ impl SpircTask {
         self.session.dealer().close().await;
     }
 
+    async fn handle_resolve_context(&mut self, context_uri: String) {
+        if context_uri.contains("spotify:show:") || context_uri.contains("spotify:episode:") {
+            return; // not supported by apollo stations
```
Comment (roderickvd) [inline connect/src/spirc.rs:425]: Something to return an Err for?

File: connect/src/state.rs [hunk 2]
```diff
@@ -141,35 +148,24 @@ impl ConnectState {
...
-                    supports_set_backend_metadata: false, // TODO: impl
+                    supports_set_backend_metadata: false,
                     supports_hifi: MessageField::none(),
 
                     command_acks: true,
                     ..Default::default()
                 }),
                 ..Default::default()
             },
+            prev_tracks: VecDeque::with_capacity(SPOTIFY_MAX_PREV_TRACKS_SIZE),
```
Comment (roderickvd) [inline connect/src/state.rs:164]: Just dropping what you may already know: this will pre-allocate enough memory for the `VecDeque` to hold that many items, but it won't be a bounded queue.

File: connect/src/state.rs [hunk 3]
```diff
@@ -194,6 +190,54 @@ impl ConnectState {
...
+            }
+
+            if self.player.is_paused && !self.player.is_playing {
+                restrictions.disallow_resuming_reasons.clear();
+                restrictions.disallow_pausing_reasons = vec!["not_playing".to_string()]
+            }
+        }
+    }
+
+    // todo: is there maybe a better or more efficient way to calculate the hash?
```
Comment (roderickvd) [inline connect/src/state.rs:232]: Not 100% sure but my thinking is this: `VecDeque` implements `Hash` so you could make a smart pointer like `struct Queue(VecDeque)` and derive `Hash` on it. Then implement `Deref` on it so you can work with the `VecDeque` directly.

File: connect/src/spirc.rs [hunk 4]
```diff
@@ -1081,13 +1080,13 @@ impl SpircTask {
...
 
-        self.connect_state.player.next_tracks.clear();
+        self.connect_state.next_tracks.clear();
         self.connect_state.player.track = MessageField::none();
 
         let index = cmd.playing_track_index as usize;
         self.connect_state.set_shuffle(cmd.shuffle);
         if cmd.shuffle {
-            self.connect_state.set_current_track(index)?;
+            self.connect_state.set_current_track(index, false)?;
```
Comment (roderickvd) [inline connect/src/spirc.rs:1093]: That `bool` here - was it a remnant from the past? I remember we had something like it in `spirc` to indicate whether we should update the state or not. Never was a fan of it, because it's not very clear what the argument does.

**Comment by roderickvd** [comment]
Curious: when shuffling is enabled, does Spotify provide the shuffled list of tracks? Or do we need to shuffle ourselves, "broadcast" the shuffled queue, and potentially un-shuffle again when requested?

I remember `libzespot-java` had this shuffle implementation with a reversible randomiser.

File: connect/src/spirc.rs [hunk 5]
```diff
@@ -449,6 +456,14 @@ impl SpircTask {
                         }
                     }
                 },
+                _ = async { sleep(Duration::from_millis(VOLUME_UPDATE_DELAY_MS)).await }, if self.update_volume => {
```
[the remark this answers is not in the document]
Comment (photovoltex) [reply connect/src/spirc.rs:407]: > why does the volume update need to be delayed?

I pretty much copied the behavior from the web-player to resolve 429 errors when updating the player state to fast. checked what the client does, and it actually just fires the request like they are nothing... 

anyhow before i did send `PLAYER_STATE_CHANGED` updates. Which quickly resulted in the before mentioned 429 errors. For that reason i switch to the delay. In a local version i switch to a different update reason, so i will see if i can fire the request like the client does.

Currently there is also a "funny" bug (not librespot related) with the web-player. If you update the volume in a different client the web-player position doesn't handle the position of the track correct and jumps ahead. The desktop client seems to behave as expected tho.

Will just check for the 429 errors and see if the different update reason fixes the problem or if the delay has to stay^^

_oh and thx for all the reviews so far, even tho this is still a incomplete state_

[the remark this answers is not in the document]
Comment (photovoltex) [reply connect/src/spirc.rs:407]: So we still run into 429 errors, but before the the volume updates stopped after the first 429 error. So both methods seem fine to me.

So either we keep the delay or just fire until we run in 429. I would be fine with both. Just need a decision here. 
Personally i like the delay because it prevents 429 and it seems sane to just send the update once in a debounce.

File: connect/src/spirc.rs [hunk 6]
```diff
@@ -1246,7 +1245,7 @@ impl SpircTask {
             .connect_state
             .context
             .as_ref()
-            .ok_or(ConnectStateError::NoContext)?;
+            .ok_or(StateError::NoContext(false))?;
```
[the remark this answers is not in the document]
Comment (photovoltex) [reply connect/src/spirc.rs:1252]: I tried a enum struct here, but it did feel annoying to always specify the field if i just want to decide between two values. But because i might add an context for autoplay next. I might automatically convert this into an enum struct by which this should be more explanatory.

The value current is the shuffle value, so if the shuffle context or normal context was used.

File: connect/src/spirc.rs (hunk 4 above)
Comment (photovoltex) [reply connect/src/spirc.rs:1093]: Same as above, decides if the current track should be set from the current or shuffle context. Will probably change soon. And yeah especially from a code review perspective this is horrible. Will see to improve these parts^^

File: connect/src/spirc.rs (hunk 1 above)
Comment (photovoltex) [reply connect/src/spirc.rs:425]: I'm currently working at the autoplay portion and how to handle it. And will probably do exactly that for the method

File: connect/src/spirc.rs [hunk 7]
```diff
@@ -137,6 +138,7 @@ pub struct SpircLoadCommand {
 const CONTEXT_FETCH_THRESHOLD: u32 = 5;
 
 const VOLUME_STEP_SIZE: u16 = 1024; // (u16::MAX + 1) / VOLUME_STEPS
+const VOLUME_UPDATE_DELAY_MS: u64 = 2000;
```
[the remark this answers is not in the document]
Comment (photovoltex) [reply connect/src/spirc.rs:139]: absolutly, sometimes forget that some structs can still be `const`, because `Vec` always doesn't work with const or static. Will adjust  it after we decide if we keep the delay or remove it^^

File: connect/src/spirc.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (photovoltex) [reply connect/src/spirc.rs:407]: > Sanity check: does this work as intended? The Tokio docs mention that the timer should be pinned if used in a loop (here: in a loop). Or does async { sleep.await() } differ from &mut sleep in that it's not polled but blocks?

I didn't go that deep into the implementation. It behaves like i want it to. The delay is intented as debounce. So that any other request is handled before and only after the sleep finishes we update the volume once. And so on. So the sleep seems to get canceled by tokio after another future wins. That how it looks from the outside.

If we keep the delay i will investigate the point in more detail and check if it actually behaves like intended.

**Comment by photovoltex** [comment]
> I remember librespot-java had this shuffle implementation with a reversible randomiser.

Yeah `librespot-java` does it that way. I would probably stay at the current solution, unless reversible shuffle is preferred or a better solution,  and just figure out how to only hold the refs in the shuffle context. By that we only have to shuffle once every time it gets enabled.

File: connect/src/state.rs (hunk 2 above)
Comment (roderickvd) [reply connect/src/state.rs:160]: Yes, I mean with a fixed size. I don't think you can do that without an array, some crate or an own implementation.

**Comment by roderickvd** [comment]
> > I remember librespot-java had this shuffle implementation with a reversible randomiser.
> 
> Yeah `librespot-java` does it that way. I would probably stay at the current solution, unless reversible shuffle is preferred or a better solution,  and just figure out how to only hold the refs in the shuffle context. By that we only have to shuffle once every time it gets enabled.

No preference. If this works, all good to me!

**Comment by photovoltex** [comment]
good god... autoplay and all the possible states is something else... I really have to revisit most of the code, because i pretty much lost the overview what is where in place. So far it does work quite decently tho.

There is only one weird thing that i couldn't solve for now. After playing all 50 autoplay tracks (or just skipping), the next autoplayed context that we retrieve, seems to be nearly identical. So there might be a missing understanding from my side what the endpoint want's from me. Will probably look into it again the next days.

**Comment by photovoltex** [comment]
So, now we also handle repeat context and track. The logic is based on how spotify does things. I will probably have to document all the new state handling way more then now. And i would also like to go over the code and split it up into more files, currently we just have two ~1k+ files, which is fine in itself, but i find it a bit overwhelming if for example one only wants to adjust a smal section.

So yeah, the next steps will be stabilizing, testing, documenting and a whole lot of cleanup :D

**Comment by roderickvd** [comment]
So you're saying it's feature complete? 👀 🤩

**Comment by photovoltex** [comment]
I would think so? When i cleanup, i will probably check again. But the main features, in addition to track repeat, should be there and working. 

There are probably still some cases that are not handled yet. For example, i only tested with an android device, the web-player and an linux desktop client. As android did send some other commands then desktop and web, there might still be some other commands that aren't covered yet.

**Comment by photovoltex** [comment]
So i found a small road blocker, some requests require a `uid` to be available. But the `resolve-context` endpoint (that i now use to resolve the context) doesn't seem to send the `uid` when requesting for album or the collection (playlists work). The `uid` doesn't seem to be much of relevance for desktop or web. But mobile sends for the `play` command a `uid` to skip to. Because the "new" context endpoint doesn't send the `uid` we can't skip to a specified `uid`... if anyone has some info around the uid i would be happy to hear how we can retrieve it maybe form the default id. 

I already tried it with apollo and that seems to send the `uid`, in addition to more metadata. But apollo resolves more then the requested context and seems to be limited at 50 tracks. Currently i like the `resolve-context` endpoint, because it does only resolve the requested context, and resolves it completely (it doesn't seem to have a limit, or at least it does resolve a context of 5k tracks). I will probably also look into some other requests that the official clients do, so that we could maybe use a different endpoint to resolve it on another way.

**Comment by roderickvd** [comment]
Unfortunately I have no experience with that. Best advice I can offer is to read through the librespot-java or maybe librespot-go source code to see how it's done there.

I agree that the Apollo station is too limiting.

**Comment by photovoltex** [comment]
So, just added the update of the context and playlist modification to the logic. It should work fine, but i had some cases where it behaved a bit weird. So might adjust some stuff the following days.

Besides that i only have three todo left in the code:
- two in regards to replacing the mercury subscriptions for:  `spotify:user:attributes:mutated` and `spotify:user:attributes:update`
  - if anyone knows how to trigger them, I would much appreciate a info on that, otherwise i will probably just remove these todos
- and one for the reconnecting of the player state

**Info's about the reconnecting todo:**
Currently when the session or dealer dies, everything is restarted. This usually isn't much of a problem, but when playing a shuffled context, it feels weird because the queue is also reshuffled. So our previous tracks we saw in the queue, are just being replaced out of nowhere. To fix that behavior i just have to handle the send context when connecting, it's easier to just ignore it, because it is usually isn't the entire context, but for this specific case it might be a good idea to handle it.

I use the current version quite regularly and for my use case it seems to work very well. Because I use bluethooth headphones it's a bit of a pain, because librespot stops working with the headphones when disconnecting and reconnecting. But the dealer aspect with desktop, web and mobile seems to work fine.

**Comment by roderickvd** [comment]
Give us a ping when you feel you're ready to go for code review.

**Comment by photovoltex** [comment]
Hmm, okay. Will try out the new changes for about a week and look into replacing the last mercury events the following days. So around next weekend i might put the pr out of the draft state. Might also make some final cleanups to the connect state because there are still some methods that without context probably are hard to distinguish what they actually do.

And thanks for the fast response and hint on the mercury subscription. I will update here again once I'm finished to a degree where we could merge it^^

**Comment by photovoltex** [comment]
Just found a part of my code that handled the updated of the context incorrect, which turned out to break the playback of artists. I put a quick fix on it, which just resolves the problem for now. But i will have to revisited a portion of the code and adjust it accordingly to handle multiple pages before falling back to autoplay or stopping the playback.

**Comment by photovoltex** [comment]
So, this might be a state that is worthwhile reviewing. 

In a previous version i already replaced the attribute mutation and updates that were still related to mercury. So mercury is now completely replace with the dealer for the `Spirc`.

The latest updates just revisited the initial take-over handling. I did also look into the transfer error in regards to multiple librespot instances mentioned by @YutongGu in  #1394. But that seemed to be fixed? Or at least i couldn't reproduce it anymore. Besides that there was an annoying bug where a mobile device just stole the playback, which should also be fixed.

I left a single todo (the before mentioned reconnect/shuffle todo) and a fixme where it technically works, but is just a workaround cause of missing knowledge what exactly the web-player requires to behave correctly.

I might still make some changes to the branch over the course of the week if i find some bugs that can be easily fixed.

Already massive thanks for anyone reviewing the code changes in advance, because they kinda escalated _just a bit_ ^^;

**Comment by PocketMiner82** [comment]
Hey @photovoltex, I tested out your PR and I must say that it looks awesome, so many bugs fixed. I (currently) only found two bugs:
1. search for a song using the normal search while connected to librespot. tap on the song to play. it does not play and the following error is logged:
  ```
  [2024-11-24T18:05:56Z ERROR librespot_connect::spirc] couldn't handle connect state command: Invalid state { could not find track None in context of 20 }
  ```
2. try to move a song in the `Next from: ...` queue. if you do so, it will get moved but the old position will get replaced with the moved song. E. g.: Next from queue is A, B, C, D. Drag C to the beginning. Now the next from queue should be C, A, B, D. But it actually is C, B, C, D.

**Comment by b-nobis** [comment]
Hi, I also tested your PR in the Context of the MuPiBox project. There we use the Spotify web api to play on a librespot connect device. If I select an album or a playlist through the web api I get the following errors:

`WARN  librespot_connect::spirc] unknown request command: {"context":{"uri":"spotify:album:1Wstoinsm4CGJ4ybpWg8iH","url":"context://spotify:album:1Wstoinsm4CGJ4ybpWg8iH"},"endpoint":"play","logging_params":{"device_identifier":"webapi-xxxx"},"options":{"seek_to":0,"skip_to":{"track_index":0}},"play_origin":{"device_identifier":"webapi-xxxx"}}`

`WARN  librespot_connect::spirc] unknown request command: {"context":{"uri":"spotify:playlist:57ta9SFJHUNCemuhm2ncEM","url":"context://spotify:playlist:57ta9SFJHUNCemuhm2ncEM"},"endpoint":"play","logging_params":{"device_identifier":"webapi-xxx"},"options":{"seek_to":0,"skip_to":{"track_index":0}},"play_origin":{"device_identifier":"webapi-xxx"}}`

**Comment by photovoltex** [comment]
First of all, thanks for testing the branch :)

> search for a song using the normal search while connected to librespot. tap on the song to play. it does not play and the following error is logged:

I can't reproduce the bug anymore. Tho, I know that there was a bug previously which blocked playing single tracks. This was fixed in https://github.com/librespot-org/librespot/pull/1356/commits/ac10e63163b3cf1f50bb00f50ad865b0a22df23e. So maybe just update your branch and the problem might go away. 

If not, could you please provide a more detail explanation how you produced the incorrect state? The device (desktop, web, mobile) make a big difference (platform is probably unrelated). Especially mobile does things quite differently then web or desktop.

> try to move a song in the Next from: ... queue. if you do so, it will get moved but the old position will get replaced with the moved song. E. g.: Next from queue is A, B, C, D. Drag C to the beginning. Now the next from queue should be C, A, B, D. But it actually is C, B, C, D.

~That I'm aware of, sadly. One of the pain points that are out of our control after we published our connect-state. If you try that example in the desktop or web-player it works without problems, but mobile does something else with it, which results in the messed up state of the queue. I already tried to figure out why it behave like it does, but couldn't find a solution for it, yet.

The problem with every around that is, that it is updated via the `set_queue` command. So we just apply what the command sends us. So there is something not quite correct with the state for the mobile client i presume.~

Scrap that, I think i just forgot to add the "queue-uid" on the `set_queue` command. Because it works, when the items are added via the web-player, so that might actually be an easy fix.

**Comment by photovoltex** [comment]
First of all, thanks for testing the branch :)

> There we use the Spotify web api to play on a librespot connect device.

Hui... that I didn't test at all so far. In the provided case, their seems to be a missing field in the our request command defined of the `play` endpoint. I will try all player endpoints and add the remaining fields, so that the commands are de-serialized correctly.

Thanks for the reminder that the API exists^^. I totally forgot that there is another "client" besides web, desktop and mobile

**Comment by photovoltex** [comment]
The add from mobile should now work correctly and afterwards moving these tracks inside the queue shouldn't remove/overwrite tracks anymore.

I checked all web-api calls for the player and it seems that only the "Start/Resume Playback" had a problem with the `PlayCommand` model. In addition the `seek_to` field should now also be applied (seems to be web-api specific).

**Comment by PocketMiner82** [comment]
> First of all, thanks for testing the branch :)
> 
> > search for a song using the normal search while connected to librespot. tap on the song to play. it does not play and the following error is logged:
> 
> I can't reproduce the bug anymore. Tho, I know that there was a bug previously which blocked playing single tracks. This was fixed in https://github.com/librespot-org/librespot/pull/1356/commits/ac10e63163b3cf1f50bb00f50ad865b0a22df23e. So maybe just update your branch and the problem might go away. 
> 
> If not, could you please provide a more detail explanation how you produced the incorrect state? The device (desktop, web, mobile) make a big difference (platform is probably unrelated). Especially mobile does things quite differently then web or desktop.
> 
> > try to move a song in the Next from: ... queue. if you do so, it will get moved but the old position will get replaced with the moved song. E. g.: Next from queue is A, B, C, D. Drag C to the beginning. Now the next from queue should be C, A, B, D. But it actually is C, B, C, D.
> 
> ~That I'm aware of, sadly. One of the pain points that are out of our control after we published our connect-state. If you try that example in the desktop or web-player it works without problems, but mobile does something else with it, which results in the messed up state of the queue. I already tried to figure out why it behave like it does, but couldn't find a solution for it, yet.
> 
> The problem with every around that is, that it is updated via the `set_queue` command. So we just apply what the command sends us. So there is something not quite correct with the state for the mobile client i presume.~
> 
> Scrap that, I think i just forgot to add the "queue-uid" on the `set_queue` command. Because it works, when the items are added via the web-player, so that might actually be an easy fix.

```
$ target/release/librespot --help
librespot 0.5.0 dab0948 (Built on 2024-11-24, Build ID: C54gdSQ6, Profile: release)
```

I already was on the latest commit when I wrote that, unfortunately. I updated to the now latest commit, both issues still exist for me. I tested both using the Android Spotify app. The queue still gets mixed up and I still get the same error message... I can also try a different client tomorrow just to verify whether it is just a problem with the Android app, if that helps.

**Comment by b-nobis** [comment]
Now it also works with the web api 👍
But I see a lot `ERROR librespot_connect::spirc] could not dispatch connect state update: Resource has been exhausted { Response status code: 429 Too Many Requests }`.

**Comment by photovoltex** [comment]
@PocketMiner82 

> Note that re-sorting a "manually" created queue works for some reason. Only re-sorting the tracks under Next from: ... (e.g. Liked songs) produces that weird behavior.

That was a very good hint. With that i could reproduce the bug. I adjusted some stuff in regards to that. Maybe try playing a different context and try then to reproduce the bug again. I couldn't reproduce it anymore so it might be fixed now.

>  I can also try a different client tomorrow just to verify whether it is just a problem with the Android app, if that helps.

That might solve your problem. But probably doesn't solve the underlying issue. So just use it as a workaround not a solution^^

**Comment by photovoltex** [comment]
@b-nobis 

> But I see a lot ERROR librespot_connect::spirc] could not dispatch connect state update: Resource has been exhausted { Response status code: 429 Too Many Requests }

Usually this shouldn't happen _anymore_. So could i ask what you request via the web-api? This might happen if you update the state of the player a lot. Like skipping many times or loading multiple contexts in a short amount of time.

**Comment by b-nobis** [comment]
> > But I see a lot ERROR librespot_connect::spirc] could not dispatch connect state update: Resource has been exhausted { Response status code: 429 Too Many Requests }
> 
> Usually this shouldn't happen _anymore_. So could i ask what you request via the web-api? This might happen if you update the state of the player a lot. Like skipping many times or loading multiple contexts in a short amount of time.

Just checked it again, and now I don‘t see them anymore. I was when I selected a specifc playlist in our ui. Then just „play“ is called via the api and the current player state is requested every second. But maybe it was because I tested some other stuff before with two boxes running. The ui also requests a lot of playlist information via the api to show it in the menus. Maybe I just hit a request limit in general. Also wanted to reduce the calls in the ui anyway. I will monitor the behaviour further, but currently it looks good.

**Comment by photovoltex** [comment]
> the current player state is requested every second

Ah i see, so perhaps its a combination out of your and librespots requests. Do you use the token retrieved by the login5 auth_token method? Because thats the token that is also used internally to update the state and retrieve additional information.

Later down the line I plan to add an option to listen to the remote and local state changes (will be another pr after this is merged). So when you have access to an spirc instance, you could just listen to the changes instead of polling the state :D

**Comment by PocketMiner82** [comment]
> @PocketMiner82
> 
> > Note that re-sorting a "manually" created queue works for some reason. Only re-sorting the tracks under Next from: ... (e.g. Liked songs) produces that weird behavior.
> 
> That was a very good hint. With that i could reproduce the bug. I adjusted some stuff in regards to that. Maybe try playing a different context and try then to reproduce the bug again. I couldn't reproduce it anymore so it might be fixed now.
> 
> > I can also try a different client tomorrow just to verify whether it is just a problem with the Android app, if that helps.
> 
> That might solve your problem. But probably doesn't solve the underlying issue. So just use it as a workaround not a solution^^

@photovoltex I pulled the latest changes and now tested different clients.

## Android app:
I can only reproduce the re-sorting bug in my "Liked songs" playlist. All others I tested work. Resorting an artist playlist also works. I also noticed that sometimes a "No internet connection available." popup pops up only when trying to play the "Liked songs" playlist. That only happens when connected to librespot. In fact, I've never seen that popup before. I'm still unable to select a song to play from the search: I clicked on the search tab at the bottom and then just searched for e.g. "never gonna". then i selected "Never gonna give you up" that spotify showed in the results. the song does not play and said error is logged.

## Web player (https://open.spotify.com):
re-sorting does not work, no matter the playlist I tried. Resorting an artist playlist or the "manual" queue works. Picking a song manually works. Autoplay also works, but only if enabled via command line tag (can't find a toggle in the web player UI to turn autoplay on or off).

## Linux app:
re-sorting never works. not even the green bar that appears when you drag a song is shown. re-sorting only works if I'm not connected to librespot. Picking a song manually works. Autoplay only works if enabled via command line tag. The UI toggle is ignored. I tried to reconnect after changing the toggle and even restarted librespot.

## Windows app (Microsoft store):
re-sorting only works for artist playlists and the "manual" queue. Picking a song manually works. Autoplay only works if enabled via command line tag. The UI toggle is ignored. I tried to reconnect after changing the toggle and even restarted librespot.
<br><br>
we all really like it, if every single client produces a different behavior, don't we? xD

**Comment by b-nobis** [comment]
> > the current player state is requested every second
> 
> Ah i see, so perhaps its a combination out of your and librespots requests. Do you use the token retrieved by the login5 auth_token method? Because thats the token that is also used internally to update the state and retrieve additional information.

We have our own OAuth access-token retrieval in our app and pass it to the librespot binary with the `-k` option. Not sure how this is then internally used in librespot. 

> Later down the line I plan to add an option to listen to the remote and local state changes (will be another pr after this is merged). So when you have access to an spirc instance, you could just listen to the changes instead of polling the state :D

Also thought about something like this, when I saw the open MPRIS PR. With this we could retrieve the information directly from librespot instead of the Spotify API.

**Comment by photovoltex** [comment]
So... resorting should hopefully work on all platforms with these changes. I did test it on my side and it seemed to work fine. It's a semi optimal solution in my opinion, but as close as we get without using the `pathfinder` endpoint. _Unless someone else finds a way to retrieve the actual uid of an item._

**Comment by photovoltex** [comment]
And with that the search result we resolve, should now expect the result from the search in each client. Additionally i could cleanup a workaround for the single track and autoplay context :D

Thx again for reporting the issues^^

**Comment by photovoltex** [comment]
> Also, I do believe that when playing a song from search, that it continues playing other results from the search (which can result in the same song being played multiple times, e. g. from different albums or dozens of remixes) instead of creating an autoplay based on the selected song.

I would actually say the behavior of librespot is not wrong. But yeah web-player and android seem to not actually play from the search context. Just checked what happens If we would run into autoplay for the search and it seems to fail. So I will rewrite it so that we always just play the track provided by a search. Seems easier anyways after implementing the other solution xD.

But mobile really is a special client for the dealer implementation...

**Comment by photovoltex** [comment]
I disabled logout support for now, because there is no proper logic in place to logout from a session. We could solve that afterwards, but for now it should probably stay disabled so it doesn't get in the way of merging these changes^^

**Comment by PocketMiner82** [comment]
very nice work @photovoltex! playing from recent searches works now. this PR also seems to fix #1205 then :D

just noticed one small bug introduced with the latest changes: if you play a song from recent searches or search, then everything looks fine, you can click the queue, shuffle and repeat buttons:
Screenshot_2024-11-28-09-10-49-540_com spotify music-edit
but when you skip to the next song, then the queue, shuffle and repeat buttons get grayed out and are no longer clickable but it is still possible to skip to the next or previous songs:
Screenshot_2024-11-28-09-20-24-914_com spotify music-edit

**Comment by photovoltex** [comment]
That's an intended behavior because you switched to the autoplay context.

We could probably argue if it makes sense to disabled the queue (don't even know exactly why that happens). But I would argue shuffle and repeat don't make much sense when you are playing an infinite context.

**Comment by PocketMiner82** [comment]
> That's an intended behavior because you switched to the autoplay context. 
Ah, I didn't knew that.

> We could probably argue if it makes sense to disabled the queue (don't even know exactly why that happens). But I would argue shuffle and repeat don't make much sense when you are playing an infinite context.
I personally do think that it makes sense to not disable the queue button because you could/should be able to re-sort the autoplay queue.
The only reason I could come up with why repeat could be useful is that you would be able to repeat a single song that is in the queue.
I'd also argue that shuffle isn't needed for a (already random) context.

Also, the normal behavior of the Spotify app when not connected to librespot is to disable the repeat and shuffle buttons but leave the queue button enabled.
Now the question is: Do we want librespot to try to mimic the exact behavior of the official clients or do we want the additional feature to enable repeating of a song in the queue (if it is even possible to only enable the repeat button)? I'd argue it's better to try to mimic the exact behavior of the official clients because of consistency. What do you think @photovoltex?

**Comment by photovoltex** [comment]
I adjusted the handling yet again on that part. It might now hopefully behave similar to the other clients.
 
Additionally i fixed the weird behavior when going to the previous track, without there being a prev track. There is a restriction set, that technically forbids the client to do it anyways... but mobile does seem to ignore it :D

**Comment by PocketMiner82** [comment]
@photovoltex The behavior seems to be the same as on the official clients now - the buttons get grayed out except for the queue button. Very nice! 

I can also say now that the UI autoplay switch is also ignored when using the Android app. autoplay only works when forcing via `--autoplay on`. log when toggling the autoplay switch off and on again in the Android app:
```
[2024-11-30T08:50:35Z TRACE librespot_core::mercury] mercury response <spotify:user:attributes:mutated> is handled by dealer
[2024-11-30T08:50:35Z TRACE librespot_connect::spirc] Received attribute mutation for autoplay but key was not found!
[2024-11-30T08:50:36Z TRACE librespot_core::mercury] mercury response <spotify:user:attributes:mutated> is handled by dealer
[2024-11-30T08:50:36Z TRACE librespot_connect::spirc] Received attribute mutation for autoplay but key was not found!
```

<br><br>

Also, when autoplay is turned off, I see these errors when selecting a song from search:
```
[2024-11-30T09:01:41Z INFO  librespot_playback::player] <We Are The People> (267354 ms) loaded
[2024-11-30T09:01:42Z ERROR librespot_connect::spirc] failed to resolve context '': Requested entity was not found { Response status code: 404 Not Found }
[2024-11-30T09:01:42Z ERROR librespot_connect::spirc] ContextError: Invalid state { context is not available. shuffle: Default }
```
skipping to the next song then causes these errors (i think skip should be disabled when there are no songs left in the queue):
```
[2024-11-30T09:04:55Z INFO  librespot_connect::spirc] Not playing next track because there are no more tracks left in queue.
[2024-11-30T09:04:55Z ERROR librespot_connect::spirc] failed to handle request: Invalid state { context is not available. shuffle: Default }
```

<br><br>

it also seems like that the official app loads the autoplay recommendations not when clicking on the search result (as librespot does) but after skipping to the next song. so if autoplay is on and you already selected a song before connecting to librespot and did not skip to the next song and then connect to librespot, you get these errors after connecting:
```
[2024-11-30T09:06:31Z INFO  librespot_playback::player] <We Are The Champions - Remastered 2011> (179200 ms) loaded
[2024-11-30T09:06:32Z ERROR librespot_connect::spirc] failed to resolve context '': Requested entity was not found { Response status code: 404 Not Found }
[2024-11-30T09:06:32Z ERROR librespot_connect::spirc] ContextError: Invalid state { context is not available. shuffle: Default }
```
skipping to the next song also does not work (because there is no queue). this error gets logged:
```
[2024-11-30T09:07:55Z INFO  librespot_connect::spirc] Not playing next track because there are no more tracks left in queue.
[2024-11-30T09:07:55Z ERROR librespot_connect::spirc] failed to handle request: Invalid state { context is not available. shuffle: Default }
[2024-11-30T09:07:55Z ERROR librespot_connect::spirc] failed resolving context <context_uri: , resolve_uri: Some(""), autoplay: true, update: true>: Client specified an invalid argument { Response status code: 400 Bad Request }
[2024-11-30T09:07:55Z ERROR librespot_connect::spirc] ContextError: Invalid state { context is not available. shuffle: Default }
```

**Comment by photovoltex** [comment]
> I can also say now that the UI autoplay switch is also ignored when using the Android app. autoplay only works when forcing via --autoplay on. log when toggling the autoplay switch off and on again in the Android app:

The info is still retrieved via mecury. In the future we probably would want to switch to the ucs info retrieval. I also saw that behavior before, while testing but currently it does seem to send the data as expected. 

Funnily enough, for myself autoplay sometimes is enable and sometimes not, even tho I didn't change if autoplay was enabled or not.

> Also, when autoplay is turned off, I see these errors when selecting a song from search:

Ugh, that's not so good. Already got to reproduce it. Don't know why that didn't occur when i testing. Will look into it.

> i think skip should be disabled when there are no songs left in the queue

Before these changes it was disabled, but it did feel a bit wrong to not be able to skip to the next track. I will adjust the logging messages accordingly.

> it also seems like that the Android app loads the autoplay recommendations differently than librespot. The app loads the recommended songs after skipping to the next song. Librespot directly loads them when clicking on a search result.

Huh... I looked into it what the mobile client actually send... For the first played track from the search it sends 40 tracks all delimited by delimiter-tracks. So in total 80 tracks. Anyhow meaning we probably just need to add a delimiter and the mobile client should display our content as expected. I also tested if the mobile client without autoplay would maybe play the search-context, but no. It just stops after skipping to the next tracks.

**Comment by PocketMiner82** [comment]
@photovoltex now the recommendations load exactly the same as in the Android app. That means #1205 can now definitely also be closed when merging this PR :D

Unfortunately I noticed a new bug since the last update (which was not there before I updated):
1. When clicking on a song from recent searches and then trying to transfer playback back to the Android app it does not work. When you then select another song, it suddenly transfers the playback to the Android app. If you don't do that, you are no longer able to control librespot (e. g. pause) until you restart the Android app.
Log after selecting another song (after trying to transfer playback to the Android app):
```
[2024-12-01T08:23:36Z INFO  librespot_playback::player] Loading <Live Is Life (Live)> with Spotify URI <spotify:track:7fCjVnzKfFecNfJ745u3MH>
[2024-12-01T08:23:37Z INFO  librespot_playback::player] <Live Is Life (Live)> (465833 ms) loaded
[2024-12-01T08:25:49Z INFO  librespot_connect::spirc] device became inactive
[2024-12-01T08:25:49Z WARN  librespot_core::dealer] No subscriber for msg.uri: social-connect/v2/broadcast_status_update
[2024-12-01T08:25:49Z WARN  librespot_connect::spirc] failed filling up next_track during stopping: context is not available. type: Default
[2024-12-01T08:25:51Z WARN  librespot_core::dealer] No subscriber for msg.uri: social-connect/v2/broadcast_status_update
```

2. When you pause before trying to transfer playback back, it enters (I think) the same weird state but this time you cannot resume. When you then select another song, it suddenly transfers the playback to the Android app.
Log after selecting another song (after trying to transfer playback to the Android app):
```
[2024-12-01T08:30:19Z INFO  librespot_playback::player] Loading <We Will Rock You - Remastered 2011> with Spotify URI <spotify:track:4pbJqGIASGPr0ZpGpnWkDn>
[2024-12-01T08:30:19Z INFO  librespot_playback::player] <We Will Rock You - Remastered 2011> (122066 ms) loaded
[2024-12-01T08:30:40Z INFO  librespot_connect::spirc] device became inactive
[2024-12-01T08:30:40Z WARN  librespot_core::dealer] No subscriber for msg.uri: social-connect/v2/broadcast_status_update
[2024-12-01T08:30:40Z WARN  librespot_connect::spirc] failed filling up next_track during stopping: context is not available. type: Default
[2024-12-01T08:30:41Z WARN  librespot_core::dealer] No subscriber for msg.uri: social-connect/v2/broadcast_status_update
```

This seems to only happen when playing a song from recent searches, I could not reproduce it otherwhere (not even in the normal search).

**Comment by photovoltex** [comment]
Funnily, that is one of the issues I encountered myself, but ignored it with the reasoning of "it's probably just a development state that will not happen in the wild :^)"

I tried a bit around, fixed some other incorrect states and behavior but didn't find a way to mitigate the issue regarding transferring the playback to the mobile app. I would suspect that it has to do with some incorrect state. Will try to find a solution the next days.

Big thanks again for all the testing and additional issue reports^^

**Comment by YutongGu** [comment]
Awesome work here! I've been playing around with this and I've found that that there's issues playing podcasts. This was tested by playing an episode from 'The Daily' and it would just continuously skip tracks. Here's my output. Any ideas?

```
[2024-12-02T19:48:09Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:0QCBV9G9U7zcMpQQlQ1svF")>: ()
[2024-12-02T19:48:09Z WARN  librespot_core::dealer] No subscriber for msg.uri: social-connect/v2/broadcast_status_update
[2024-12-02T19:48:09Z INFO  librespot_connect::spirc] session update: <Ok(NEW_SESSION)> for self, current session_id 91f8087d952e4fccbb439dd437ce5cf0, new session_id 01c353cbe58934afca6af2e7dcf1a641
[2024-12-02T19:48:09Z INFO  librespot_connect::spirc] Not playing next track because there are no more tracks left in queue.
[2024-12-02T19:48:09Z ERROR librespot_connect::spirc] could not dispatch player event: Invalid state { context is not available. type: Default }
[2024-12-02T19:48:10Z ERROR librespot_connect::spirc] could not parse session_update: Invalid state { Unknown enum variant name: `WIFI_BROADCAST_CHANGED` at 1:11 }
[2024-12-02T19:48:10Z ERROR librespot_connect::spirc] failed resolving context <resolve_uri: <Some("spotify:show:3IM0lmZxpFAY7CwMuv9H4g")>, context_uri: <spotify:show:3IM0lmZxpFAY7CwMuv9H4g>, autoplay: <true>, update: <true>>: Service unavailable { tried resolving not allowed context: "spotify:show:3IM0lmZxpFAY7CwMuv9H4g" }
[2024-12-02T19:48:10Z WARN  librespot_connect::spirc] failed filling up next_track during stopping: context is not available. type: Default
[2024-12-02T19:48:11Z WARN  librespot_connect::state::context] current track was removed, setting pos to last known index
[2024-12-02T19:48:14Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:14Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:0QCBV9G9U7zcMpQQlQ1svF")>: ()
[2024-12-02T19:48:14Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:14Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:02UL6q2ZSd2GVRcEof0OxR")>: ()
[2024-12-02T19:48:15Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:15Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:3YBgeJsIBZk7GPRIaAXXvs")>: ()
[2024-12-02T19:48:15Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:15Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:3FUMELhLmENjNH4DLuXnDa")>: ()
[2024-12-02T19:48:16Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:16Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:6dRm8iM1hNMBH93XsiaMbb")>: ()
[2024-12-02T19:48:17Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:17Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:2Y0LwuZTk5pDp2A5AJZFu7")>: ()
[2024-12-02T19:48:18Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:18Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:6L0UavBmtlggPSq5WKwjp7")>: ()
[2024-12-02T19:48:19Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:19Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:5Esudj52STTftmOIP9Hlb1")>: ()
[2024-12-02T19:48:19Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unknown, error: StatusCode(502) }
[2024-12-02T19:48:19Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:episode:1XEFMcqlZOdYxNnFw6GI6A")>: ()
```

**Comment by photovoltex** [comment]
@YutongGu Thanks for reporting^^

Oh yeah podcasts/episodes don't work currently. I thought to have tested it against dev, but tested it again just now and it seems to work on dev... Soooo i suppose that's an open point that did overlook or tested wrong back then.

I will take it into the open points/issues

**Comment by YutongGu** [comment]
I did some playing around and I narrowed the cause to the the `request` function in `spclient.rs.` The issue was that podcasts/episodes were unable to get metadata from spotify's servers. After making the following changes, podcasts would start working.

```
             // `vodafone-uk` but we've yet to discover how we can find that value.
             // For the sake of documentation you could also do "product=free" but
             // we only support premium anyway.
-            if options.metrics {
-                let _ = write!(
-                    url,
-                    "{}product=0&country={}",
-                    separator,
-                    self.session().country()
-                );
-            }
+
+            let _ = write!(
+                url,
+                "{}product=0&country={}",
+                separator,
+                self.session().country()
+            );
+
 
             // Defeat caches. Spotify-generated URLs already contain this.
-            if options.salt && !url.contains("salt=") {
-                let _ = write!(url, "{separator}salt={}", rand::thread_rng().next_u32());
+            if !url.contains("salt=") {
+                let _ = write!(url, "&salt={}", rand::thread_rng().next_u32());
             }
 
             let mut request = Request::builder()
```

These changes undo some of the work in [85a68c8](https://github.com/photovoltex/librespot/commit/85a68c8fe39845edb86f81f3e0d6065f7eb99524). I understand the full context for these changes but it seems like there may be a bug in the implementation.

**Comment by roderickvd** [comment]
I've said it before and I'll say it again: mega job guys. First of all towards @photovoltex but also to everyone contributing with feedback and ideas.

It feels like we've past a first shakedown period. How about we merge this to `dev` and get the second round of shakedown going, when more users will get to use it on the bleeding edge?

**Comment by roderickvd** [comment]
_@photovoltex I'd like to contact you 1-on-1 but can't find your address. Would you send me a message?_

**Comment by YutongGu** [comment]
I think that's a good idea to merge this in! It would be good to have more people try it out, leave feedback, and implement fixes of their own.

Separately, I wanted to bring attention to another issue. I'm not sure if it only affects me but when I pause the song while connected to librespot, the app on my phone will show it as paused but the seek/playback bar will keep seeking forward as if the song was still playing. It seems like the app is correctly reporting the `is_paused`, `is_playing`, and `is_buffering` states when you pause, perhaps something else intuitively controls whether the seek bar is continuously moving forward.

**Comment by photovoltex** [comment]
> I've said it before and I'll say it again: mega job guys. First of all towards @photovoltex but also to everyone contributing with feedback and ideas.
> 
> It feels like we're past a first shakedown period. How about we merge this to `dev` and get the second round of shakedown going, when more users will get to use it on the bleeding edge?

@roderickvd (_i messaged you and my email is now also publicly available_)

If everyone is fine with the current state being merged in to `dev`, I would have nothing against it. Tho I would like to do a final cleanup of some clones that are not required. So that we could maybe merge it the next days?

**Comment by photovoltex** [comment]
So, did a final refactoring of a section I wasn't so happy with, might be worse, might be better, will probably see with time. The previous version did try to reduce cpu usage and with refactoring it should now use less memory, but might use the cpu more when for example, skipping a lot of tracks in the queue.

I additionally improved the context handling again. And for myself, the issue @PocketMiner82 described around the transferring of the recent search seems to be resolved by that :D

That will probably be the last changes for now, unless I find some major points. But the initial impl is probably now in a _complete_ state^^

**Comment by PocketMiner82** [comment]
> I additionally improved the context handling again. > And for myself, the issue @PocketMiner82 described around the transferring of the recent search seems to be resolved by that :D

@photovoltex yes, it is indeed working now :)

**Comment by roderickvd** [comment]
Awesome so let's get it in `dev`. Would you consider squashing it?

**Comment by PocketMiner82** [comment]
Hmmm... I think I found a new issue, happened to me 3 times today (but for some reason never before): I was listening to the liked songs playlists for some time and suddenly the music stops playing in the middle of a song. the following errors got logged:

```
Dec 06 10:39:52 rpi-3a librespot[1607]: [2024-12-06T09:39:52Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:00 rpi-3a librespot[1607]: [2024-12-06T09:40:00Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:08 rpi-3a librespot[1607]: [2024-12-06T09:40:08Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:16 rpi-3a librespot[1607]: [2024-12-06T09:40:16Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:24 rpi-3a librespot[1607]: [2024-12-06T09:40:24Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:32 rpi-3a librespot[1607]: [2024-12-06T09:40:32Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:40 rpi-3a librespot[1607]: [2024-12-06T09:40:40Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:48 rpi-3a librespot[1607]: [2024-12-06T09:40:48Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:40:56 rpi-3a librespot[1607]: [2024-12-06T09:40:56Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
Dec 06 10:41:04 rpi-3a librespot[1607]: [2024-12-06T09:41:04Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
```

Note that the wifi of this device (Raspberry Pi 3 A+) is a bit unstable for me, sometimes it doesn't respond for more than 20 seconds... Maybe that's why the `wait timeout exceeded`. I thought I'll report it regardless, maybe some timeout can be increased 🤷

**Comment by photovoltex** [comment]
> Awesome so let's get it in `dev`. Would you consider squashing it? 

Sure thing. But did anyone look over the code or do we just merge it? I could understand why, the changes are a bit too drastic/large to review. But just wanted to hear what the stance in regards to that is^^

**Comment by roderickvd** [comment]
In an ideal world I'd like to run through the code, but I don't have a lot of time for it in the coming weeks. So I thought that it's better to get it in and we can still place code comments on GitHub after the merge.

**Comment by photovoltex** [comment]
Sounds reasonable. Feel free to merge whenever fits best :)

**Comment by photovoltex** [comment]
> Hmmm... I think I found a new issue, happened to me 3 times today (but for some reason never before): I was listening to the liked songs playlists for some time and suddenly the music stops playing in the middle of a song. the following errors got logged:
> 
> ```
> Dec 06 10:39:52 rpi-3a librespot[1607]: [2024-12-06T09:39:52Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:00 rpi-3a librespot[1607]: [2024-12-06T09:40:00Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:08 rpi-3a librespot[1607]: [2024-12-06T09:40:08Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:16 rpi-3a librespot[1607]: [2024-12-06T09:40:16Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:24 rpi-3a librespot[1607]: [2024-12-06T09:40:24Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:32 rpi-3a librespot[1607]: [2024-12-06T09:40:32Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:40 rpi-3a librespot[1607]: [2024-12-06T09:40:40Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:48 rpi-3a librespot[1607]: [2024-12-06T09:40:48Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:40:56 rpi-3a librespot[1607]: [2024-12-06T09:40:56Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> Dec 06 10:41:04 rpi-3a librespot[1607]: [2024-12-06T09:41:04Z ERROR librespot_playback::player] Skipping to next track, unable to get next packet for track <SpotifyId("spotify:track:4GewRLEiI4BDTQsoH8BRVV")>: SymphoniaDecoder("Deadline expired before operation could complete { wait timeout exceeded }")
> ```
> 
> Note that the wifi of this device (Raspberry Pi 3 A+) is a bit unstable for me, sometimes it doesn't respond for ~15 seconds... Maybe that's why the `wait timeout exceeded`. I thought I'll report it regardless, maybe some timeout can be increased 🤷

That should probably be unrelated to these changes. But if they appear again we can open an issue then^^

**Comment by YutongGu** [comment]
> Hmmm... I think I found a new issue, happened to me 3 times today (but for some reason never before): I was listening to the liked songs playlists for some time and suddenly the music stops playing in the middle of a song. the following errors got logged...

I can report that this issue occurred for me as well:
```
[2024-12-06T21:34:29Z INFO  librespot_playback::player] Loading <Guy For That (Feat. Luke Combs)> with Spotify URI <spotify:track:6StwwqB84sJeLr7tZDTxEX>
[2024-12-06T21:34:32Z ERROR librespot_core::audio_key] Audio key response timeout
Rate limited 1 logs
[2024-12-06T21:34:37Z ERROR librespot_core::session] Connection to server closed.
[2024-12-06T21:35:01Z WARN  librespot_core::dealer] Websocket peer does not respond.
[2024-12-06T21:35:06Z ERROR librespot_playback::player] Unable to read audio file: Symphonia Decoder Error: Deadline expired before operation could complete { wait timeout exceeded }
[2024-12-06T21:35:08Z WARN  librespot] Spirc shut down unexpectedly
[2024-12-06T21:35:08Z ERROR librespot_core::session] Transport endpoint is not connected (os error 107)
[2024-12-06T21:35:18Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2024-12-06T21:35:23Z INFO  librespot_core::session] Authenticated as '1219828745' !
Rate limited 1 logs
[2024-12-06T21:35:31Z INFO  librespot_core::spclient] Resolved "guc3-spclient.spotify.com:443" as spclient access point
[2024-12-06T21:35:39Z INFO  librespot_connect::spirc] active device is <> with session <0d5cfc65538b301a627f3c9d7dce54b2>
[2024-12-06T21:38:11Z WARN  librespot_connect::state::context] switching to active context had issues: Invalid state { context is not available. type: Default }
---- 2024-12-06 21:38:14.953302: Now starting Spotify ----
```

**Comment by photovoltex** [comment]
Hui that's a lot of errors and warning in one spot. Seems all be related to sort of timeout or unresponsive network connection. Can both of you maybe try to reproduce these issues on the dev branch?

I will look into it if there might be some changes that unintentionally affect the player. But from the errors in the log it sounds more like network issues.

**Comment by photovoltex** [comment]
I did also find a weird behavior from the context-resolver... if you request a playlist that contains tracks and episodes, only the tracks will be resolved. The response seems to not contain any info about the episodes... I will probably not solve it anymore in context of this PR, so might be moved out into a new issue afterwards.

**Comment by photovoltex** [comment]
There is also an oversight with the current impl in relation to shuffle and a context with multiple pages. For example playing an artist with shuffle doesn't work yet as one would expect. That probably needs a revisit at some point in the future. Adjusting the current impl would probably add another 100+ lines to the current PR, which i would like to prevent for now^^

**Comment by photovoltex** [comment]
Looked again at this comment (https://github.com/librespot-org/librespot/pull/1356#issuecomment-2427617758), and it might be a better solution in the end, when we play a shuffled context we usually don't need the default context. I had hopped we could just keep refs to the original tracks in a vec, but that collides with every state modification you still want to do. 

That might be a nice next task to do after this initial state is merged and we iterate on improving performance and stability :D

**Comment by photovoltex** [comment]
Continuing development here (https://github.com/photovoltex/librespot/tree/improve-dealer) so that this PR is only the basic integration (with some new features provided by the dealer)

**Comment by roderickvd** [comment]
Drumroll for merging, coming up in 3... 2....

**Comment by photovoltex** [comment]
Well, and now we wait for issues that we didn't spotted during testing/development
