### PR TITLE
Fix `--device` argument to various backends

### LINKED ISSUE #936: Device argument to pipe sink does not work
contrary to the documentation --device/-d does not work when building without default options.
This means the pipe sink receives None as a path and opens stdout instead

### PR DESCRIPTION
**Pull request by roderickvd**
Fixes #936.

This removes the `The ``--{}`` / ``-{}`` option is not supported by the included audio backend(s), and has no effect.` message that was introduced by @JasonLG1979. I couldn't find an easy and maintainable way of implementing this in all backends (like a `fn supports_device() -> bool where Self:: Sized` method in the `Sink` trait) and thought that low code complexity trumps here.

Also some small cleanups and the change that `pipe` now creates a file if it didn't already exist.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -748,46 +748,14 @@ fn get_setup() -> Setup {
...
-        feature = "alsa-backend",
-        feature = "rodio-backend",
-        feature = "portaudio-backend"
-    ))]
     if let Some(ref value) = device {
         if value == "?" {
             backend(device, format);
             exit(0);
-        } else if value.is_empty() {
-            empty_string_error_msg(DEVICE, DEVICE_SHORT);
```
Comment (JasonLG1979) [inline src/main.rs:768]: You still need that. It guards against empty strings as a device. `--device ""` is a valid argument as far as getopts is concerned but will fail.

Comment (roderickvd) [reply src/main.rs:768]: Good catch, I'll put that back in.

**Comment by heeen** [comment]
This works for me

**Comment by JasonLG1979** [comment]
LGTM
