### PR TITLE
Fix: use extended-metadata endpoint to acquire metadata

### LINKED ISSUE #1620: Fetching audiobooks/podcast metadata results in 502 Bad Gateway
### Description
When fetching the metadata of an audio book or a podcast, librespot throws an error "502 Bad Gateway"

### Version
librespot-metadata = "0.7.1"

### How to reproduce
```rust
Show::get(session, &spotify_id)
      .await
      .map_err(|e| Error::new(ErrorKind::Other, format!("Failed to fetch show: {}", e)))
```
-> `Failed to fetch show: Unknown error { Response status code: 502 Bad Gateway }`
Tested with the following URIs:
- `spotify:show:1IyAJYcVhVN4owCMPNWjSV` (Audio book)
- `spotify:show:1dQMmMennmPctlQzHDCiZ8` (Audio book)
- `spotify:show:3RWaVT0v1SK6iALTtUK8bQ` (Podcast)

However, using the librespot standalone binary, it is able to get the information and even playback the episodes
```
[2025-10-29T14:09:33Z DEBUG librespot_core::http_client] Requesting https://gew4-spclient.spotify.com:443/context-resolve/v1/spotify:show:1IyAJYcVhVN4owCMPNWjSV
[2025-10-29T14:09:33Z DEBUG librespot_connect::spirc] handling next context Some("spotify:show:1IyAJYcVhVN4owCMPNWjSV")
[2025-10-29T14:09:33Z DEBUG librespot_connect::state::context] updated context Default to <Some("spotify:show:1IyAJYcVhVN4owCMPNWjSV")> (286 tracks)
[2025-10-29T14:09:33Z DEBUG librespot_connect::context_resolver] last item of type <Default>, finishing state setup
[2025-10-29T14:09:33Z DEBUG librespot_connect::state::transfer] active track is <spotify:episode:3v7RM7AtydrnsjeTEvlGO6> with index Ok(0) in Default context, has 286 tracks
[2025-10-29T14:09:33Z DEBUG librespot_connect::state::transfer] setting up next and prev: index is at Some(0) while shuffle false
[2025-10-29T14:09:33Z DEBUG librespot_connect::state] reset_playback with active ctx <Default> fill_up ctx <Default>
[2025-10-29T14:09:33Z DEBUG librespot_connect::state::tracks] set track to: spotify:episode:3v7RM7AtydrnsjeTEvlGO6 at 0 of 286 tracks
[2025-10-29T14:09:33Z DEBUG librespot_connect::state::tracks] finished filling up next_tracks (80)
[2025-10-29T14:09:33Z DEBUG librespot_connect::state] updated connect play status playing: true, paused: true, buffering: true
[2025-10-29T14:09:33Z DEBUG librespot_core::http_client] Requesting https://gew4-spclient.spotify.com:443/connect-state/v1/devices/....?product=0&country=DE&salt=2378509623
[2025-10-29T14:09:36Z TRACE librespot_core::dealer] dealer request hm://connect-state/v1/player/command
[2025-10-29T14:09:36Z TRACE librespot_core::dealer::protocol] message was sent with gzip encoding
[2025-10-29T14:09:36Z TRACE librespot_core::dealer::protocol] websocket request: Object {
        "command": Object {
            "endpoint": String("resume"),
            "logging_params": Object {
                "command_id": String("f955f96e87ee87e53e4418a2eb8d2f0c"),
                "device_identifier": String("...."),
            },
        },
        "message_id": Number(810386418),
        "play_on_secondary_stream": Null,
        "sent_by_device_id": String("...."),
        "target_alias_id": Null,
    }
[2025-10-29T14:09:36Z DEBUG librespot_connect::spirc] handling: 'endpoint: resume' from ....
[2025-10-29T14:09:36Z DEBUG librespot_connect::spirc] SpircTask::set_volume(32767)
[2025-10-29T14:09:36Z DEBUG librespot_playback::player] command=Play
[2025-10-29T14:09:36Z DEBUG librespot_core::dealer::manager] replying to ws request: Success
[2025-10-29T14:09:36Z TRACE librespot_playback::player] == Starting sink ==
[2025-10-29T14:09:36Z TRACE librespot_connect::spirc] ==> Playing
[2025-10-29T14:09:37Z DEBUG librespot_connect::state] updated connect play status playing: true, paused: false, buffering: false
[2025-10-29T14:09:37Z DEBUG librespot_connect::state] update position to 0:26 at 14:09:37.174
[2025-10-29T14:09:37Z DEBUG librespot_core::http_client] Requesting https://gew4-spclient.spotify.com:443/connect-state/v1/devices/....?product=0&country=DE&salt=1378805215
[2025-10-29T14:09:40Z TRACE librespot_core::dealer] dealer request hm://connect-state/v1/player/command
[2025-10-29T14:09:40Z TRACE librespot_core::dealer::protocol] message was sent with gzip encoding
[2025-10-29T14:09:40Z TRACE librespot_core::dealer::protocol] websocket request: Object {
        "command": Object {
            "endpoint": String("pause"),
            "logging_params": Object {
                "command_id": String("4ec715eb3c97e061f03e328158cbc432"),
                "device_identifier": String("...."),
            },
            "options": Object {},
        },
        "message_id": Number(810390192),
        "play_on_secondary_stream": Null,
        "sent_by_device_id": String("..."),
        "target_alias_id": Null,
    }
[2025-10-29T14:09:40Z DEBUG librespot_connect::spirc] handling: 'endpoint: pause' from ...
[2025-10-29T14:09:40Z DEBUG librespot_core::dealer::manager] replying to ws request: Success
[2025-10-29T14:09:40Z DEBUG librespot_playback::player] command=Pause
[2025-10-29T14:09:40Z TRACE librespot_playback::player] == Stopping sink ==
```

### Host (what you are running `librespot` on):
- OS: Arch Linux
- Platform: x86-64

### LINKED ISSUE #1623: Librespot fails to play any tracks
### Description
Looks like Spotify changed something again on their servers and is causing librespot to stop playing tracks. I can successfully connect but tracks do not play. On initial connect there is a log that indicates `setup of state failed: invalid state` and a `400 bad request` with the message that the client specified an invalid argument. Skipping to the next track causes librespot to fail with continuous `Track should be available, but no alternatives found`

Appears that Spotify's servers made some breaking changes to their API. Thoughts?

### Version
dev, v0.7.0, v0.7.1

### How to reproduce
1. Launch librespot in release mode with no additional parameters except "--name"
2. Connect with Spotify Connect on iPhone Spotify app (Have not tested on android)
3. In the app, select a song to play
5. Selected song does not play

### Log
```
[2025-11-06T18:03:15Z INFO  librespot] librespot 0.7.1 9142e69 (Built on 2025-11-06, Build ID: c7oa5hj0, Profile: release)
[2025-11-06T18:03:15Z TRACE librespot] Command line argument(s):
[2025-11-06T18:03:15Z TRACE librespot] 		verbose
[2025-11-06T18:03:15Z TRACE librespot] 		name "test"
[2025-11-06T18:03:15Z DEBUG librespot_core::session] new Session
[2025-11-06T18:03:15Z DEBUG librespot_discovery::server] Zeroconf server listening on 0.0.0.0:45795
[2025-11-06T18:03:15Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2025-11-06T18:03:15Z DEBUG librespot_playback::player] new Player [0]
[2025-11-06T18:03:15Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2025-11-06T18:03:15Z INFO  librespot_playback::audio_backend::rodio] Using Rodio sink with format S16 and cpal host: ALSA
[2025-11-06T18:03:15Z INFO  librespot_playback::audio_backend::rodio] Using audio device: default
[2025-11-06T18:03:15Z DEBUG librespot_playback::audio_backend::rodio] Rodio sink was created
[2025-11-06T18:03:24Z DEBUG librespot_discovery::server] POST "/" {}
[2025-11-06T18:03:24Z DEBUG librespot_core::session] Shutdown: Invalidating session
[2025-11-06T18:03:24Z DEBUG librespot::component] new MercuryManager
[2025-11-06T18:03:24Z DEBUG librespot::component] new ChannelManager
[2025-11-06T18:03:24Z DEBUG librespot_core::session] new Session
[2025-11-06T18:03:24Z DEBUG librespot_connect::spirc] new Spirc[0]
[2025-11-06T18:03:24Z DEBUG librespot_playback::player] command=SetSession
[2025-11-06T18:03:24Z DEBUG librespot::component] new DealerManager
[2025-11-06T18:03:24Z DEBUG librespot_core::session] drop Session
[2025-11-06T18:03:24Z DEBUG librespot::component] drop ChannelManager
[2025-11-06T18:03:24Z DEBUG librespot::component] drop MercuryManager
[2025-11-06T18:03:24Z DEBUG librespot::component] new SpClient
[2025-11-06T18:03:24Z DEBUG librespot_core::spclient] Client token unavailable or expired, requesting new token.
[2025-11-06T18:03:24Z DEBUG librespot_core::http_client] Requesting https://clienttoken.spotify.com/v1/clienttoken
[2025-11-06T18:03:25Z DEBUG librespot_core::spclient] Received a granted token
[2025-11-06T18:03:25Z TRACE librespot_core::spclient] Got client token: GrantedTokenResponse { token: "AACDGhgNWBXLGpXr5cXw9gKyG7IZiAvnSEo0U7bD1+xQ+Hukh+GjKLdceMHw3QQc1y1AL6qwVKIEcRVbGsGCcIEqNlQ4/MixMLxl9pejgw02uc8/B9D20Zr7KHac5IAfKDdrWGi4RISZNlOFDAcaHgjlZLTX06a6ACzo051US58NSd3NfKnPDGiN0NgwAvJfPRKFMx6LaNeOeY6exyqZv13ErJnAxQlh+l2SW8h2a82GvoSUYoxiz9HFrZ4wcC7GOEIMRPTG0RrIkLEW5PkDTC2Syvt+w7J6+ddYXk1PrhAY/3yOqZDg5IRJNOXjV72bxEygrt28LzM=", expires_after_seconds: 1216800, refresh_after_seconds: 1209600, domains: [TokenDomain { domain: "spotify.com", special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }, TokenDomain { domain: "spotify.net", special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }], special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[2025-11-06T18:03:25Z DEBUG librespot::component] new ApResolver
[2025-11-06T18:03:25Z DEBUG librespot_core::http_client] Requesting https://apresolve.spotify.com/?type=accesspoint&type=dealer&type=spclient
[2025-11-06T18:03:25Z WARN  librespot_core::apresolve] Failed to resolve all access points, using fallbacks
[2025-11-06T18:03:25Z WARN  librespot_core::apresolve] Resolve access points error: Service unavailable { client error (Connect) }
[2025-11-06T18:03:25Z INFO  librespot_core::session] Connecting to AP "ap.spotify.com:443"
[2025-11-06T18:03:25Z DEBUG librespot_core::connection] Connection to AP established.
[2025-11-06T18:03:25Z DEBUG librespot_core::connection] Authenticating with AP using AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS
[2025-11-06T18:03:25Z INFO  librespot_core::session] Authenticated as '1219828745' !
[2025-11-06T18:03:25Z DEBUG librespot::component] new Login5Manager
[2025-11-06T18:03:25Z DEBUG librespot_core::http_client] Requesting https://login5.spotify.com/v3/login
[2025-11-06T18:03:25Z TRACE librespot_core::session] Received Ping
[2025-11-06T18:03:25Z TRACE librespot_core::session] keep-alive state: PendingPong, timeout in 60.0
[2025-11-06T18:03:25Z DEBUG librespot_core::session] Session strong=5 weak=6
[2025-11-06T18:03:25Z INFO  librespot_core::session] Country: "US"
[2025-11-06T18:03:25Z TRACE librespot_core::session] Received product info: {
        "jam": "1",
        "collection": "1",
        "image-url": "https://i.scdn.co/image/{file_id}",
        "is-tuna": "0",
        "network-operator-premium-activation": "1",
        "is-standalone-audiobooks": "0",
        "jam-social-session": "EXPANDED",
        "rating-access": "1",
        "financial-product": "pr:premium,tc:0,rt:v2_US_default_individual-basic-1m-1m_10.99_USD_default",
        "app-developer": "0",
        "unrestricted": "1",
        "ad-formats-preroll-video": "0",
        "audiobook-onboarding-completed": "0",
        "shows-collection-jam": "1",
        "shuffle": "0",
        "video-device-blacklisted": "0",
        "mobile": "1",
        "arsenal_country": "1",
        "ab-ad-player-targeting": "1",
        "key-caching-max-count": "10000",
        "catalogue": "premium",
        "prefetch-strategy": "18",
        "video-cdn-sampling": "100",
        "streaming": "1",
        "ab-watch-now": "0",
        "incognito_mode_timeout": "21600",
        "metadata-link-lookup-modes": "0",
        "license-acceptance-grace-days": "30",
        "on-demand-trial-in-progress": "0",
        "audio-preview-url-template": "https://p.scdn.co/mp3-preview/{id}",
        "capping-bar-threshold": "3601",
        "explicit-content": "1",
        "head-files-url": "https://heads-fa-tls13.spotifycdn.com/head/{file_id}",
        "prefetch-keys": "1",
        "sidebar-navigation-enabled": "0",
        "name": "Spotify Premium",
        "loudness-levels": "1:-5.0,0.0,3.0:-2.0",
        "player-license-v2": "premium",
        "user-profile-show-invitation-codes": "0",
        "nft-disabled": "1",
        "audio-quality": "1",
        "public-toplist": "7",
        "is-cheetara": "0",
        "setup-headphones-changes": "0",
        "shuffle-algorithm": "FRESH",
        "video-manifest-url": "https://spclient.wg.spotify.com/manifests/v6/{type}/sources/{source_id}/options/supports_drm",
        "shows-collection": "1",
        "yl-kids-restricted-content": "0",
        "browse-overview-enabled": "1",
        "dma-mode-available": "0",
        "dsa-mode-enabled": "0",
        "type": "premium",
        "enable-crossfade": "1",
        "key-memory-cache-mode": "1:15,300",
        "payments-locked-state": "0",
        "playlist-annotations-markup": "0",
        "publish-playlist": "1",
        "ads": "0",
        "head-file-caching": "1",
        "is-pigeon": "0",
        "mobile-payment": "0",
        "high-bitrate": "1",
        "dma-mode-enabled": "0",
        "restrict-playlist-collaboration": "0",
        "streaming-only-premium": "0",
        "pick-and-shuffle": "0",
        "preferred-locale": "en-us",
        "enable-annotations": "2",
        "has-audiobooks-subscription": "0",
        "is-puffin": "0",
        "offline": "1",
        "social-session": "1",
        "enable-annotations-read": "0",
        "ab_recently_played_feature_time_filter_threshold": "com.spotify.gaia=30,driving-mode=120,spotify%3Ainternal%3Astartpage=30",
        "send-email": "0",
        "player-license": "premium",
        "ugc-abuse-report": "1",
        "apply-child-content-restrictions": "0",
        "key-caching-auto-offline": "0",
        "prefetch-window-max": "2",
        "publish-activity": "0",
        "dsa-mode-available": "0",
        "libspotify": "1",
        "radio": "1",
        "widevine-license-url": "https://spclient.wg.spotify.com/widevine-license/v1/video/license",
        "autoplay": "1",
        "is_email_verified": "1",
        "ad-session-persistence": "1",
        "key-caching-max-offline-seconds": "1800",
        "obfuscate-restricted-tracks": "0",
        "on-demand": "1",
        "storage-size-config": "10240,90,500,3",
        "ugc-abuse-report-url": "https://support.spotify.com/abuse/?uri={uri}",
        "filter-explicit-content": "0",
        "employee-free-opt-in": "0",
        "payments-initial-campaign": "default",
        "remote-control": "6",
        "social-session-free-tier": "0",
        "is-thalia": "1",
        "video-keyframe-url": "http://keyframes-fa.cdn.spotify.com/keyframes/v1/sources/{source_id}/keyframe/heights/{height}/timestamps/{timestamp_ms}.jpg",
    }
[2025-11-06T18:03:25Z DEBUG librespot::component] new MercuryManager
[2025-11-06T18:03:25Z TRACE librespot_core::mercury] mercury response <hm://pusher/v1/connections/YTk0YThmZTVjY2IxOWJhNjFjNGMwODczZDM5MWU5ODc5ODJmYmJkMytBUCt0Y3A6Ly8wYWIxNDgzMy5pcC5ndWMzLnNwb3RpZnkubmV0OjUwMTYrRjJDMjEwOEI4M0UxQTMxM0RDNUQ1RDRFQzkyMzJDQ0FGNzA2REE4Qjk1MDUxNjEwNUM2QzNFN0EwNTQ3NkJDNg%3D%3D> is handled by dealer
[2025-11-06T18:03:25Z TRACE librespot_core::login5] Got auth token: Token { access_token: "BQC8brYClX3JYVjT0gBZWak0TdVGWD7wN5OCuefUDnuUFwqjeaEd6zHFiuaYntEEnC_5NIhrEVO7kjymTJCbbdREkB_wCEPyNIBvJMrBpGQOYeBHhlY9W8ev6naB0eVRBDCusSIl1IiJEp5qBVnAf1-vVBYKO89xikh5Fk8QOhsATMmF904nNULIC1UNxEBnJlmuvxu-sv2xaY6sGSb8MvOGcieWjcHY0uIRSf1TCesy__1Zdok7v-JOAhyhDTRg0lHkBSpyR1Tclza3Bg54OHx_Hf3TP-Jpddj1yKbF-BUT8u45sC0yCLVqr6v2QOPHxRLK1EwExefeJUjgIuXHC1EoswPrc9nLXmFmvIjE-onyEyFJIMK2nH0W9ySBGNfqIuY_BakPnnw8tf8SAnYxbxLv7xyc", expires_in: 3600s, token_type: "Bearer", scopes: [], timestamp: Instant { tv_sec: 470144, tv_nsec: 769129754 } }
[2025-11-06T18:03:25Z DEBUG librespot_connect::spirc] SpircTask::set_volume(32767)
[2025-11-06T18:03:25Z DEBUG librespot_playback::player] command=AddEventSender
[2025-11-06T18:03:25Z DEBUG librespot_playback::mixer::mappings] Input volume 32767 mapped to: 3.16%
[2025-11-06T18:03:25Z DEBUG librespot_core::dealer::manager] Launching dealer
[2025-11-06T18:03:25Z DEBUG librespot_core::http_client] Requesting https://apresolve.spotify.com/?type=accesspoint&type=dealer&type=spclient
[2025-11-06T18:03:25Z WARN  librespot_core::apresolve] Failed to resolve all access points, using fallbacks
[2025-11-06T18:03:25Z WARN  librespot_core::apresolve] Resolve access points error: Service unavailable { client error (Connect) }
[2025-11-06T18:03:26Z TRACE librespot_core::dealer] Sent ping
[2025-11-06T18:03:26Z TRACE librespot_connect::spirc] Received connection ID update: "NTE3MTUyZmEtN2FkYy00NTZlLWE4NzUtMjhlM2Y3YTMyZDRhK2RlYWxlcit0Y3A6Ly8wYWIxNDhlOC5pcC5ndWMzLnNwb3RpZnkubmV0OjU3MDArOEFGODc2OEQ1QkMzMDdFRjMwMkQ0OEM4ODgwMDQwQTg5MTQzQTBGNTUxNDAzRTNCNkM5MzgzM0YxQTQwOUUyQg=="
[2025-11-06T18:03:26Z DEBUG librespot_core::http_client] Requesting https://apresolve.spotify.com/?type=accesspoint&type=dealer&type=spclient
[2025-11-06T18:03:26Z WARN  librespot_core::apresolve] Failed to resolve all access points, using fallbacks
[2025-11-06T18:03:26Z WARN  librespot_core::apresolve] Resolve access points error: Service unavailable { client error (Connect) }
[2025-11-06T18:03:26Z INFO  librespot_core::spclient] Resolved "spclient.wg.spotify.com:443" as spclient access point
[2025-11-06T18:03:26Z DEBUG librespot_core::http_client] Requesting https://spclient.wg.spotify.com:443/connect-state/v1/devices/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3?product=0&country=US&salt=1887626871
[2025-11-06T18:03:26Z TRACE librespot_core::dealer] Received pong
[2025-11-06T18:03:26Z TRACE librespot_core::dealer] dealer request hm://connect-state/v1/player/command
[2025-11-06T18:03:26Z TRACE librespot_core::dealer::protocol] message was sent with gzip encoding 
[2025-11-06T18:03:26Z TRACE librespot_core::dealer::protocol] websocket request: Object {
        "command": Object {
            "data": String("CjQIABAAGAAlAAAAACoKCgNqYW0SA29mZiobChNjb250ZXh0X2VuaGFuY2VtZW50EgROT05FEqoCCKCG2dKlMxCqJRkAAAAAAAAAACABKpICCiRzcG90aWZ5OnRyYWNrOjdnZjVmZm1TcUtRQkRua21TZTJEdDcSEGQ2YzA2ZGIzYTRkMzgwOTkaEO6bKlgWL0Unuac35EwEkTkiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEgoNY29udGV4dF9pbmRleBIBMBrMawoXCgASABoAIgAqADIAOgdjb25uZWN0QgASmmsKLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaBI3Y29udGV4dDovL3Nwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCIAKq1qIpICCiRzcG90aWZ5OnRyYWNrOjdnZjVmZm1TcUtRQkRua21TZTJEdDcSEGQ2YzA2ZGIzYTRkMzgwOTkaEO6bKlgWL0Unuac35EwEkTkiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEgoNY29udGV4dF9pbmRleBIBMCKSAgokc3BvdGlmeTp0cmFjazowaHRORE5OUmtGbVF1RVNrcTRlb3FqEhBlMWM5NmU2ODczODBjYzEyGhAJQ4xoJApNAJ7GzjY4I2NPIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhIKDWNvbnRleHRfaW5kZXgSATEikgIKJHNwb3RpZnk6dHJhY2s6MVl6SXBxd25qNU04cXlsd24xVHI5WhIQNzRlN2M2MDZkNjMxNWIwMhoQQPWHl1zXQ0OADBNddBHHzyI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCISCg1jb250ZXh0X2luZGV4EgEyIpICCiRzcG90aWZ5OnRyYWNrOjN4T2kwWWhEUkVLUlVSRkhvTmFBT1ESEDZkMmQ2ZTRjYzMzNTQwZmIaEHR9HxTaZ0Msu4s70W2rfeAiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEgoNY29udGV4dF9pbmRleBIBMyKSAgokc3BvdGlmeTp0cmFjazo0R1VhRzNkZjluYnJqNzdHS0VCNzZqEhBkNjUwOWEyMGU4YjUzOWE4GhCaKlmG8N5DAKLuipwSwMk7IjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhIKDWNvbnRleHRfaW5kZXgSATQikgIKJHNwb3RpZnk6dHJhY2s6MjJZdlVjR3pWTGp0SzN1MmZTTUFachIQMzM0YWM0MzhiNjBlOGJiMBoQQ0p1+6kHSz+EBTM4gvx78SI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCISCg1jb250ZXh0X2luZGV4EgE2IpICCiRzcG90aWZ5OnRyYWNrOjV2c2FzcEY2d0laT1BXTkNkSFVGTFASEDA0YTZmZmVhMmNkNTI5NGIaELT0F0EfK0RCpeHN1r88u4kiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEgoNY29udGV4dF9pbmRleBIBNyKSAgokc3BvdGlmeTp0cmFjazozQkNzTk0ydzZIY0NiclZXbGhqVHBrEhAxNzVlNjAxNTk4MDRlZGI2GhB2gel8vXlEELEslpz5PuHWIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhIKDWNvbnRleHRfaW5kZXgSATgikgIKJHNwb3RpZnk6dHJhY2s6NmRBTmNRMDB1aWlXb0JEWVZyc0d2ehIQZWYwNmVhNGU1MWY2Y2YxNxoQzFhQBJRdQYSeCqUnFpXgfSI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCISCg1jb250ZXh0X2luZGV4EgE5IpMCCiRzcG90aWZ5OnRyYWNrOjRKbjJDZFpZcXRJc1BwSVJZQjFvNDcSEDRmZWY0NTQ0ZTRlNTM3NmEaEJt42zuhbEYcu28j/jyw6WciOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMTAikwIKJHNwb3RpZnk6dHJhY2s6MW1VVHBEZTNFOHBNTDYzN3pPRkw1RBIQNzViODRhN2U4NjQ0ODJmYhoQLQCF6Ol/RGesfoTeB5yn0SI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIxMSKTAgokc3BvdGlmeTp0cmFjazoyVzVkU3VNN0REZFd5bWp6WnNJQ0JuEhA5YzgwNTBkMWQ3MGMxYmU5GhBgftPqSRFLXoyyEQ5i7QWlIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjEyIpMCCiRzcG90aWZ5OnRyYWNrOjFzMEIwZGtaSGZ5blNjcExPMFV6SlgSEDM1YjkzYjU3ODM4M2Q4ZGUaEC+zVmW2906ZjH7FaUwF++0iOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMTMikwIKJHNwb3RpZnk6dHJhY2s6M1I2eU5pY3NacldGOHlibDAyaW1jQhIQZmMxYjAyZTFjMDRhMWQyMRoQfrbGLUziRS+u+Q04F9KItSI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIxNCKTAgokc3BvdGlmeTp0cmFjazo0Nm9EQmRkaHd1MGdmRnIyejFmdmg1EhAwY2E1MzEyOTE1MzNlM2UyGhCG0VYPNZtG8L4T4zPdLJ/XIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjE1IpMCCiRzcG90aWZ5OnRyYWNrOjZwYW1hZkQ5cDBLN0ZIZkpQejZUWUYSEDk3NWZhMDNhMjBlNDZhYmYaENJ6eEJzOUlPr9QtUZ3WAu0iOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMTYikwIKJHNwb3RpZnk6dHJhY2s6NXowTFNEcFBwR3djMlp5Skhwc0UzShIQMzRhM2I2MTMzMDYzOGIyMhoQttbPik+JT1SfMEf35XRQFyI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIxNyKTAgokc3BvdGlmeTp0cmFjazo2Y1VKbXpVMjRHb3JSaGVLZ2htTmtZEhAyM2FkM2UyZDdmMjFmYmViGhDL/EYCs+VCbp/tCQylWNS4IjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjE4IpMCCiRzcG90aWZ5OnRyYWNrOjVYbE1qNDlQM2pqbVhwQWRWR09MeVcSEGM5ODAzMjhmYjMxMjdmOTMaEMO8yS/fMUFQqAIdcluHMmIiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMTkikwIKJHNwb3RpZnk6dHJhY2s6NnlLaFJpa0JIWHk0TXlMeTRLOEt1WBIQNmUyODk2NzEyZmZjNzY2ZhoQ144YaM0xTsWmonUUCw4nVyI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIyMCKTAgokc3BvdGlmeTp0cmFjazoxOU1rd01yUmpPNzc3M3pwdUdzczFvEhAwOGYzMjYwNTE2YjE0Zjg0GhAmCh2BKFtLfKngJyQVyCyGIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjIxIpMCCiRzcG90aWZ5OnRyYWNrOjBPV2hLdnZzSHB0dDZ2bm5OVVNNOWESEDlmYjcxMWRhNjgwMzMzMzkaEBr+5EB5pEJhnEhmXFE7zegiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMjIikwIKJHNwb3RpZnk6dHJhY2s6MGhjMnM3c2JQVG9tZWdEWHBJeVNvaxIQYjc3MDA3ZjYyZjI1NmRhYxoQCRyvG3iFQSO0b2LgNZ9AjCI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIyMyKTAgokc3BvdGlmeTp0cmFjazo0Z2k4MWNnYVUwWG1lazFJdU9FTk01EhA4NzYxMDRiNjgzOTYwYjk2GhCMD8M/HUVAL4aIELG1ntwJIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjI0IpMCCiRzcG90aWZ5OnRyYWNrOjdKMEdnV1BNZjVPVFNKSzZ1WHhGZTASEDI2ODBmY2FkNDE3NTkxMGUaEP3Z/jhUMEdAhlue3CvD1HAiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMjUikwIKJHNwb3RpZnk6dHJhY2s6NzE0dEYwVnQ5b2hDOXVXd0V5SVJBbxIQNTMwNDE5MGQ4ODgzNzJiORoQ5pDzr+v1QZCOCUtN3mP7ZCI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIyNiKTAgokc3BvdGlmeTp0cmFjazoyMGRrZWJCdFBSNEFKOHZWb3M0MUd3EhBiYWIzNTQxNTMyMGM1MmQ3GhBB097Ox8hP95wkiaK+p5CwIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjI3IpMCCiRzcG90aWZ5OnRyYWNrOjVqZmhMQ1NJRlVPNG5kek5SaDR3NEcSEGU5NDRkMWJkMjdlM2VmYWIaEK575ffsDE/fnf83t6LZHbIiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMjgikwIKJHNwb3RpZnk6dHJhY2s6MFZCS2JndDdROGZ2UjRCNURydlZwaBIQZmQ4NGJjMDJmNGQyOWE0MBoQHoecyJ+URC+p/NUMDcgXmyI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIyOSKTAgokc3BvdGlmeTp0cmFjazoyUVpNT1phWENON0dRanIzcUtXQXdBEhBjNWQwNmQ5ZjdlMzAyYzE3GhBdzJjO40dBAKhKYyTOuQaEIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjMwIpMCCiRzcG90aWZ5OnRyYWNrOjdBZU0xQkdZTTdlbXJxbVFuMVB1V3YSEDgzYWIzZWJjMTRjNDVkZjIaEPkz09EVqEZUoeSuICopZzsiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMzEikwIKJHNwb3RpZnk6dHJhY2s6MlJvTVFBcnoxVjZ1aU1lckQ4MnNLbRIQMWE4NDY4ZWU3NDJmMzQwZBoQXgNNYPK7SL25jP1046pQ+iI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIzMiKTAgokc3BvdGlmeTp0cmFjazo0YTJ1cVZscFJDaEhqMzJFakpMdTdHEhAxYTI0MjNiZTYzYjRkNGY4GhCIv4p0AohMOLAmS26fUu5MIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjMzIpMCCiRzcG90aWZ5OnRyYWNrOjBIRXl0R1FNM2JHMXZLeEVSN0lnVksSEGZkNGQxMmFmNzgwZmU5ZmIaEBcibPrl903LjLnYn0K5BCwiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMzQikwIKJHNwb3RpZnk6dHJhY2s6ME5kRWRzWFM5amJYMWhudWZhd1owehIQMTlhZTUxOGI4MDE0MmJiNRoQGhWMrgu6TDe9tY2rLDcs1yI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIzNSKTAgokc3BvdGlmeTp0cmFjazoxT1lIWEN1SGR6SGpwSHFIbFkxZzFyEhA0M2UwNGVhNDkwN2RkNDdkGhA734xQJV5EupgOjA1NRCNxIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjM2IpMCCiRzcG90aWZ5OnRyYWNrOjVBUU5xZHBsNlNFVjlyQUhXeTdVOXcSEGZlMDY2ZmM1ZmNjNzhhZDgaELfQUT8lRUp0iNyNy1lqKJYiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICMzcikwIKJHNwb3RpZnk6dHJhY2s6MzExR3Z4cHVldXU0THZXWVo3Znd2YRIQYzY0NjA1NzkzZTExMWEwNhoQYx1rrIchQlKjB77sblpMZCI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgIzOCKTAgokc3BvdGlmeTp0cmFjazozRnE0c2hoSmRFTlFod2xMazlxb0R4EhAwN2E5NWQ2MjZlN2MyZjM5GhB4hXZ0779AAqmV6m2Ux0xzIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjM5IpMCCiRzcG90aWZ5OnRyYWNrOjNHbjF6dUhOTHRHdUdFT1h3cTBrN2USEDg1MWFiYzcwMGM3NDU5MzgaEHkGdqOcA0tnjEqepaktzXAiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICNDAikwIKJHNwb3RpZnk6dHJhY2s6NEtVTEF5bUJCSmNQUnBrMXlPNGRPRxIQOWZjYTVjYmZkOGVlZmQ2MxoQnEpSDF/QSAevjKu+85LDeiI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgI0MSKTAgokc3BvdGlmeTp0cmFjazoxRkhJWmtuT05yVjJjMjB3MHg1QVZHEhA1ZmViYTVhZjhiZjBiNDczGhA29WHXPzxAP4GWCVTR2ZVwIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjQyIpMCCiRzcG90aWZ5OnRyYWNrOjdBbXprMmhDTFUyZ1RKdnFZc1dtazcSEGNlODU2OGYwY2Q5YzliZDEaEPlE4m87UE6JoUP35Dlj+6ciOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICNDMikwIKJHNwb3RpZnk6dHJhY2s6NjVCbVVxeVB1SDRRTGZRamNvSlBGTBIQM2EzNzk5MDgyMjcyMmFhOBoQyBw8i+XHRXeWqdcYhq7JQSI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgI0NCKTAgokc3BvdGlmeTp0cmFjazo1VnQyb1haYmtRZ0ZXSDFUaWgxb2tWEhAzNzY4ZDE0YWQ3ZGU5NWE3GhDCvVZPPbdCzqi4yLES1Pd5IjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjQ1IpMCCiRzcG90aWZ5OnRyYWNrOjViN0Y1RHo1TGp4TUd2VTNuMnZxYzUSEGE0MDljNmY5YzA3YThiYTQaEKot4UCdTEocnG6qHHKK5l0iOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICNDYikwIKJHNwb3RpZnk6dHJhY2s6M1dNajhtb0lBWEpoSHN5TGFxSUlISRIQM2JkNzdjNDRjMmQ3MTA2MRoQgbh1wRuFTBWwrlLXWpA3BiI7CgplbnRpdHlfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiNwoLZGVjaXNpb25faWQSKHNzcH4wNjQyZjBkZjNjZmQ4YWE5Mzk4MmQ3YTFhMzFhMjAwZjM4ZmEiPAoLY29udGV4dF91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCITCg1jb250ZXh0X2luZGV4EgI0NyKTAgokc3BvdGlmeTp0cmFjazo1QmxHbXlzOVZxbUhaYmY3ZXN3eEcxEhA2ODBhOGI3MWMyYmYwYmE0GhC4E+bYkq1DN6sGSIUAVFfxIjsKCmVudGl0eV91cmkSLXNwb3RpZnk6c3RhdGlvbjphcnRpc3Q6NFlMdHNjWHN4YlZnaTAzMW92RERkaCI3CgtkZWNpc2lvbl9pZBIoc3NwfjA2NDJmMGRmM2NmZDhhYTkzOTgyZDdhMWEzMWEyMDBmMzhmYSI8Cgtjb250ZXh0X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIhMKDWNvbnRleHRfaW5kZXgSAjQ4IpMCCiRzcG90aWZ5OnRyYWNrOjNRRTlxeVFySWdlZnpuU2NoQVlKUEISEDRhMDFhMGQ2M2NmYmFhOTIaEH54nCFY3k8UtY910DDr+3MiOwoKZW50aXR5X3VyaRItc3BvdGlmeTpzdGF0aW9uOmFydGlzdDo0WUx0c2NYc3hiVmdpMDMxb3ZERGRoIjcKC2RlY2lzaW9uX2lkEihzc3B+MDY0MmYwZGYzY2ZkOGFhOTM5ODJkN2ExYTMxYTIwMGYzOGZhIjwKC2NvbnRleHRfdXJpEi1zcG90aWZ5OnN0YXRpb246YXJ0aXN0OjRZTHRzY1hzeGJWZ2kwMzFvdkREZGgiEwoNY29udGV4dF9pbmRleBICNDkaEGQ2YzA2ZGIzYTRkMzgwOTkqADIAIg8QABoLCOLFs8gGEIDokiY="),
            "endpoint": String("transfer"),
            "from_device_identifier": String("dcfa067efb666b0a9e0045e33e6eda9bb5a5fe6d"),
            "logging_params": Object {
                "command_id": String("d6c0a8405c494362ae577894ba422c53"),
                "interaction_ids": Array [
                    String("E198475A-E04A-456C-9C4B-8AEFDED03FEE"),
                ],
            },
            "options": Object {
                "license": String("premium"),
                "restore_paused": String("restore"),
                "restore_position": String("last_known"),
                "restore_track": String("always_play_something"),
                "retain_session": String("do_not_retain"),
            },
        },
        "message_id": Number(1515616333),
        "play_on_secondary_stream": Null,
        "sent_by_device_id": String("dcfa067efb666b0a9e0045e33e6eda9bb5a5fe6d"),
        "target_alias_id": Null,
    }
[2025-11-06T18:03:26Z DEBUG librespot_connect::spirc] successfully put connect state for a94a8fe5ccb19ba61c4c0873d391e987982fbbd3 with connection-id NTE3MTUyZmEtN2FkYy00NTZlLWE4NzUtMjhlM2Y3YTMyZDRhK2RlYWxlcit0Y3A6Ly8wYWIxNDhlOC5pcC5ndWMzLnNwb3RpZnkubmV0OjU3MDArOEFGODc2OEQ1QkMzMDdFRjMwMkQ0OEM4ODgwMDQwQTg5MTQzQTBGNTUxNDAzRTNCNkM5MzgzM0YxQTQwOUUyQg==
[2025-11-06T18:03:26Z INFO  librespot_connect::spirc] active device is <> with session <45d8a9954d454e389a895c3ac5c4cd5c>
[2025-11-06T18:03:26Z DEBUG librespot_connect::spirc] handling: 'endpoint: transfer' from dcfa067efb666b0a9e0045e33e6eda9bb5a5fe6d
[2025-11-06T18:03:26Z WARN  librespot_connect::state::context] couldn't load context info because: context is not available. type: Default
[2025-11-06T18:03:26Z DEBUG librespot_connect::spirc] found initial track <spotify:track:7gf5ffmSqKQBDnkmSe2Dt7>
[2025-11-06T18:03:26Z TRACE librespot_connect::context_resolver] added spotify:station:artist:4YLtscXsxbVgi031ovDDdh to resolver queue
[2025-11-06T18:03:26Z DEBUG librespot_connect::context_resolver] update for resolve_uri: <Some("spotify:station:artist:4YLtscXsxbVgi031ovDDdh")>, context_uri: <spotify:station:artist:4YLtscXsxbVgi031ovDDdh>, update: <Default> is already added
[2025-11-06T18:03:26Z TRACE librespot_connect::state::transfer] shuffle_seed: <None> (spotify), <None> (own)
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=EmitSessionConnectedEvent("NTE3MTUyZmEtN2FkYy00NTZlLWE4NzUtMjhlM2Y3YTMyZDRhK2RlYWxlcit0Y3A6Ly8wYWIxNDhlOC5pcC5ndWMzLnNwb3RpZnkubmV0OjU3MDArOEFGODc2OEQ1QkMzMDdFRjMwMkQ0OEM4ODgwMDQwQTg5MTQzQTBGNTUxNDAzRTNCNkM5MzgzM0YxQTQwOUUyQg==", "1219828745")
[2025-11-06T18:03:26Z DEBUG librespot_connect::state] updated connect play status playing: true, paused: true, buffering: true
[2025-11-06T18:03:26Z DEBUG librespot_connect::state] updated connect play status playing: true, paused: true, buffering: true
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=EmitSessionClientChangedEvent("65b708073fc0480ea92a077233ca87bd", "", "", "")
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=EmitVolumeChangedEvent(32767)
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=EmitAutoPlayChangedEvent(true)
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=EmitFilterExplicitContentChangedEvent(false)
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=EmitShuffleChangedEvent(false)
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=EmitRepeatChangedEvent(false, false)
[2025-11-06T18:03:26Z DEBUG librespot_core::http_client] Requesting https://spclient.wg.spotify.com:443/connect-state/v1/devices/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3?product=0&country=US&salt=2696203153
[2025-11-06T18:03:26Z DEBUG librespot_playback::player] command=Load(SpotifyUri("spotify:track:7gf5ffmSqKQBDnkmSe2Dt7"), false, 4778)
[2025-11-06T18:03:26Z DEBUG librespot_core::http_client] Requesting https://spclient.wg.spotify.com/metadata/4/track/ee9b2a58162f4527b9a737e44c049139?product=0&country=US&salt=2873679427
[2025-11-06T18:03:26Z TRACE librespot_metadata] Received metadata: Track {
        gid: Some(
            [
                238,
                155,
                42,
                88,
                22,
                47,
                69,
                39,
                185,
                167,
                55,
                228,
                76,
                4,
                145,
                57,
            ],
        ),
        name: Some(
            "It Takes A Woman",
        ),
        album: MessageField(
            Some(
                Album {
                    gid: Some(
                        [
                            207,
                            217,
                            226,
                            38,
                            16,
                            173,
                            76,
                            72,
                            152,
                            71,
                            20,
                            135,
                            152,
                            104,
                            6,
                            140,
                        ],
                    ),
                    name: Some(
                        "Higher",
                    ),
                    artist: [
                        Artist {
                            gid: Some(
                                [
                                    163,
                                    161,
                                    83,
                                    58,
                                    113,
                                    62,
                                    76,
                                    248,
                                    175,
                                    83,
                                    213,
                                    47,
                                    27,
                                    21,
                                    138,
                                    75,
                                ],
                            ),
                            name: Some(
                                "Chris Stapleton",
                            ),
                            popularity: None,
                            top_track: [],
                            album_group: [],
                            single_group: [],
                            compilation_group: [],
                            appears_on_group: [],
                            external_id: [],
                            portrait: [],
                            biography: [],
                            activity_period: [],
                            restriction: [],
                            related: [],
                            is_portrait_album_cover: None,
                            portrait_group: MessageField(
                                None,
                            ),
                            sale_period: [],
                            availability: [],
                            special_fields: SpecialFields {
                                unknown_fields: UnknownFields {
                                    fields: None,
                                },
                                cached_size: CachedSize {
                                    size: 0,
                                },
                            },
                        },
                    ],
                    type_: None,
                    label: Some(
                        "Mercury Nashville",
                    ),
                    date: MessageField(
                        Some(
                            Date {
                                year: Some(
                                    2023,
                                ),
                                month: Some(
                                    11,
                                ),
                                day: Some(
                                    10,
                                ),
                                hour: None,
                                minute: None,
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                        ),
                    ),
                    popularity: None,
                    cover: [],
                    external_id: [],
                    disc: [],
                    review: [],
                    copyright: [],
                    restriction: [],
                    related: [],
                    sale_period: [],
                    cover_group: MessageField(
                        Some(
                            ImageGroup {
                                image: [
                                    Image {
                                        file_id: Some(
                                            [
                                                171,
                                                103,
                                                97,
                                                109,
                                                0,
                                                0,
                                                30,
                                                2,
                                                222,
                                                46,
                                                48,
                                                207,
                                                114,
                                                5,
                                                180,
                                                90,
                                                11,
                                                163,
                                                135,
                                                127,
                                            ],
                                        ),
                                        size: Some(
                                            DEFAULT,
                                        ),
                                        width: Some(
                                            300,
                                        ),
                                        height: Some(
                                            300,
                                        ),
                                        special_fields: SpecialFields {
                                            unknown_fields: UnknownFields {
                                                fields: None,
                                            },
                                            cached_size: CachedSize {
                                                size: 0,
                                            },
                                        },
                                    },
                                    Image {
                                        file_id: Some(
                                            [
                                                171,
                                                103,
                                                97,
                                                109,
                                                0,
                                                0,
                                                72,
                                                81,
                                                222,
                                                46,
                                                48,
                                                207,
                                                114,
                                                5,
                                                180,
                                                90,
                                                11,
                                                163,
                                                135,
                                                127,
                                            ],
                                        ),
                                        size: Some(
                                            SMALL,
                                        ),
                                        width: Some(
                                            64,
                                        ),
                                        height: Some(
                                            64,
                                        ),
                                        special_fields: SpecialFields {
                                            unknown_fields: UnknownFields {
                                                fields: None,
                                            },
                                            cached_size: CachedSize {
                                                size: 0,
                                            },
                                        },
                                    },
                                    Image {
                                        file_id: Some(
                                            [
                                                171,
                                                103,
                                                97,
                                                109,
                                                0,
                                                0,
                                                178,
                                                115,
                                                222,
                                                46,
                                                48,
                                                207,
                                                114,
                                                5,
                                                180,
                                                90,
                                                11,
                                                163,
                                                135,
                                                127,
                                            ],
                                        ),
                                        size: Some(
                                            LARGE,
                                        ),
                                        width: Some(
                                            640,
                                        ),
                                        height: Some(
                                            640,
                                        ),
                                        special_fields: SpecialFields {
                                            unknown_fields: UnknownFields {
                                                fields: None,
                                            },
                                            cached_size: CachedSize {
                                                size: 0,
                                            },
                                        },
                                    },
                                ],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                        ),
                    ),
                    original_title: None,
                    version_title: None,
                    type_str: None,
                    availability: [],
                    special_fields: SpecialFields {
                        unknown_fields: UnknownFields {
                            fields: Some(
                                {
                                    25: UnknownValues {
                                        fixed32: [],
                                        fixed64: [],
                                        varint: [],
                                        length_delimited: [
                                            [
                                                10,
                                                16,
                                                254,
                                                53,
                                                142,
                                                169,
                                                135,
                                                226,
                                                66,
                                                77,
                                                144,
                                                33,
                                                194,
                                                102,
                                                90,
                                                6,
                                                103,
                                                183,
                                            ],
                                        ],
                                    },
                                    37: UnknownValues {
                                        fixed32: [],
                                        fixed64: [],
                                        varint: [],
                                        length_delimited: [
                                            [
                                                10,
                                                9,
                                                8,
                                                206,
                                                31,
                                                16,
                                                22,
                                                24,
                                                18,
                                                32,
                                                22,
                                                18,
                                                9,
                                                8,
                                                206,
                                                31,
                                                16,
                                                22,
                                                24,
                                                18,
                                                32,
                                                22,
                                            ],
                                        ],
                                    },
                                },
                            ),
                        },
                        cached_size: CachedSize {
                            size: 0,
                        },
                    },
                },
            ),
        ),
        artist: [
            Artist {
                gid: Some(
                    [
                        163,
                        161,
                        83,
                        58,
                        113,
                        62,
                        76,
                        248,
                        175,
                        83,
                        213,
                        47,
                        27,
                        21,
                        138,
                        75,
                    ],
                ),
                name: Some(
                    "Chris Stapleton",
                ),
                popularity: None,
                top_track: [],
                album_group: [],
                single_group: [],
                compilation_group: [],
                appears_on_group: [],
                external_id: [],
                portrait: [],
                biography: [],
                activity_period: [],
                restriction: [],
                related: [],
                is_portrait_album_cover: None,
                portrait_group: MessageField(
                    None,
                ),
                sale_period: [],
                availability: [],
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        number: Some(
            4,
        ),
        disc_number: Some(
            1,
        ),
        duration: Some(
            246986,
        ),
        popularity: Some(
            60,
        ),
        explicit: None,
        external_id: [
            ExternalId {
                type_: Some(
                    "isrc",
                ),
                id: Some(
                    "USUG12300475",
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        restriction: [],
        file: [],
        alternative: [],
        sale_period: [],
        preview: [],
        tags: [],
        earliest_live_timestamp: Some(
            1699527600,
        ),
        has_lyrics: Some(
            true,
        ),
        availability: [],
        licensor: MessageField(
            Some(
                Licensor {
                    uuid: Some(
                        [
                            254,
                            53,
                            142,
                            169,
                            135,
                            226,
                            66,
                            77,
                            144,
                            33,
                            194,
                            102,
                            90,
                            6,
                            103,
                            183,
                        ],
                    ),
                    special_fields: SpecialFields {
                        unknown_fields: UnknownFields {
                            fields: None,
                        },
                        cached_size: CachedSize {
                            size: 0,
                        },
                    },
                },
            ),
        ),
        language_of_performance: [
            "en",
        ],
        original_audio: MessageField(
            Some(
                Audio {
                    uuid: Some(
                        [
                            109,
                            171,
                            217,
                            68,
                            196,
                            86,
                            75,
                            140,
                            191,
                            199,
                            179,
                            170,
                            61,
                            104,
                            63,
                            239,
                        ],
                    ),
                    special_fields: SpecialFields {
                        unknown_fields: UnknownFields {
                            fields: Some(
                                {
                                    2: UnknownValues {
                                        fixed32: [],
                                        fixed64: [],
                                        varint: [
                                            1,
                                        ],
                                        length_delimited: [],
                                    },
                                },
                            ),
                        },
                        cached_size: CachedSize {
                            size: 0,
                        },
                    },
                },
            ),
        ),
        content_rating: [],
        original_title: Some(
            "It Takes A Woman",
        ),
        version_title: None,
        artist_with_role: [
            ArtistWithRole {
                artist_gid: Some(
                    [
                        163,
                        161,
                        83,
                        58,
                        113,
                        62,
                        76,
                        248,
                        175,
                        83,
                        213,
                        47,
                        27,
                        21,
                        138,
                        75,
                    ],
                ),
                artist_name: Some(
                    "Chris Stapleton",
                ),
                role: Some(
                    ARTIST_ROLE_MAIN_ARTIST,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        canonical_uri: Some(
            "spotify:track:7gf5ffmSqKQBDnkmSe2Dt7",
        ),
        original_video: [],
        special_fields: SpecialFields {
            unknown_fields: UnknownFields {
                fields: Some(
                    {
                        44: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [],
                            length_delimited: [
                                [
                                    18,
                                    11,
                                    8,
                                    254,
                                    224,
                                    193,
                                    165,
                                    6,
                                    16,
                                    128,
                                    131,
                                    129,
                                    41,
                                ],
                            ],
                        },
                        37: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [],
                            length_delimited: [
                                [
                                    10,
                                    9,
                                    8,
                                    206,
                                    31,
                                    16,
                                    22,
                                    24,
                                    18,
                                    32,
                                    22,
                                ],
                            ],
                        },
                        39: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [],
                            length_delimited: [
                                [],
                            ],
                        },
                        41: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [],
                            length_delimited: [
                                [
                                    10,
                                    20,
                                    10,
                                    16,
                                    109,
                                    171,
                                    217,
                                    68,
                                    196,
                                    86,
                                    75,
                                    140,
                                    191,
                                    199,
                                    179,
                                    170,
                                    61,
                                    104,
                                    63,
                                    239,
                                    16,
                                    1,
                                ],
                            ],
                        },
                        43: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [
                                0,
                            ],
                            length_delimited: [],
                        },
                    },
                ),
            },
            cached_size: CachedSize {
                size: 0,
            },
        },
    }
[2025-11-06T18:03:26Z ERROR librespot_playback::player] Track should be available, but no alternatives found.
[2025-11-06T18:03:26Z WARN  librespot_playback::player] spotify:track:<7gf5ffmSqKQBDnkmSe2Dt7> is not available
[2025-11-06T18:03:26Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyUri("spotify:track:7gf5ffmSqKQBDnkmSe2Dt7")>: ()
[2025-11-06T18:03:26Z DEBUG librespot_core::http_client] Requesting https://spclient.wg.spotify.com:443/context-resolve/v1/spotify:station:artist:4YLtscXsxbVgi031ovDDdh
[2025-11-06T18:03:26Z DEBUG librespot_core::http_client] Requesting https://spclient.wg.spotify.com:443/context-resolve/v1/spotify:station:artist:4YLtscXsxbVgi031ovDDdh
[2025-11-06T18:03:26Z DEBUG librespot_core::http_client] Requesting https://spclient.wg.spotify.com:443/context-resolve/v1/spotify:station:artist:4YLtscXsxbVgi031ovDDdh
[2025-11-06T18:03:26Z TRACE librespot_connect::spirc] ==> LoadingPause
[2025-11-06T18:03:26Z DEBUG librespot_connect::state::tracks] marking spotify:track:7gf5ffmSqKQBDnkmSe2Dt7 as unavailable
[2025-11-06T18:03:26Z ERROR librespot_connect::spirc] could not dispatch player event: Invalid state { context is not available. type: Default }
[2025-11-06T18:03:26Z DEBUG librespot_core::dealer::manager] replying to ws request: Success
[2025-11-06T18:03:27Z DEBUG librespot_connect::state] updated connect play status playing: true, paused: true, buffering: true
[2025-11-06T18:03:27Z DEBUG librespot_core::http_client] Requesting https://spclient.wg.spotify.com:443/connect-state/v1/devices/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3?product=0&country=US&salt=1407352145
```

### Host (what you are running `librespot` on):
- OS: Linux
- Platform: Lenovo T14

### Additional context

### PR DESCRIPTION
**Pull request by photovoltex**
As noticed by @michaelherger in #1621 the metadata endpoint seems to be broken again and does not contain anymore the file data.

This changes uses the extended metadata endpoint instead, which currently still contains that data.

Fixes #1623, Fixes #1620

### CODE REVIEW

**Comment by hbsagen** [comment]
Great, saved my evening. Works nicely!

**Review by kingosticks — DISMISSED** [review]

File: core/src/spclient.rs [hunk 1]
```diff
@@ -572,39 +570,67 @@ impl SpClient {
...
+    ) -> Result<BatchedExtensionResponse, Error> {
+        let endpoint = "/extended-metadata/v0/extended-metadata";
+        let res = self
+            .request_with_protobuf(&Method::POST, endpoint, None, &request)
+            .await?;
+        Ok(BatchedExtensionResponse::parse_from_bytes(&res)?)
+    }
+
+    pub async fn get_metadata(&self, kind: ExtensionKind, id: &SpotifyUri) -> SpClientResult {
+        let req = BatchedEntityRequest {
```
Comment (photovoltex) [inline core/src/spclient.rs:596]: @roderickvd I remember you wanting this to be a builder pattern. Any reason why tho or what the advantage would be?

**Comment by michaelherger** [comment]
Working in my 30s of testing.

I'd still get multiple of the following messages per second (in debug mode):

```
[2025-11-06T19:15:18Z WARN  libmdns::fsm] error sending packet Os { code: 65, kind: HostUnreachable, message: "No route to host" }
```

**Comment by michaelherger** [comment]
And works with my fork, too!

**Comment by DamianRyse** [comment]
Works pretty good for me.

**Comment by OneTrueJASH** [comment]
I can also confirm this fix works as expected. I've successfully tested it with [spotify-player](https://github.com/aome510/spotify-player) v0.21.1.

Since the `SpotifyUri` API changes were already present in the dev branch (prior to this PR), I first updated spotify-player to be compatible with those changes:
- Updated functions to use `SpotifyUri` enum instead of checking `SpotifyId.item_type`
- Pattern matching on `SpotifyUri` variants (`Track { id }`, `Episode { id }`) to extract the underlying `SpotifyId`

With those compatibility changes in place, this PR's metadata endpoint fix works perfectly. Spotify-player now successfully uses the `/extended-metadata/v0/extended-metadata` endpoint and tracks play without the "Track should be available, but no alternatives found" errors.

I'm preparing a compatibility PR for spotify-player to ensure it's ready when the librespot dev branch changes land in a release.

Thanks @photovoltex!

**Comment by photovoltex** [comment]
> Working in my 30s of testing.
> 
> I'd still get multiple of the following messages per second (in debug mode):
> 
> ```
> [2025-11-06T19:15:18Z WARN  libmdns::fsm] error sending packet Os { code: 65, kind: HostUnreachable, message: "No route to host" }
> ```

@michaelherger I don't have such warnings, so this might be something on your end then? But I wont rule out that there is still something we need to fix later down the line.

**Comment by OneTrueJASH** [comment]
> @michaelherger I don't have such warnings, so this might be something on your end then? But I wont rule out that there is still something we need to fix later down the line.

I also gave this a spin to see if I could reproduce the libmdns warnings @michaelherger mentioned:

`RUST_LOG=debug ./target/release/librespot --enable-oauth --name "test-device"`
Duration: ~60 seconds
My setup:
- macOS Tahoe 26.1 (25B78)
- rustc 1.91.0 / cargo 1.91.0

What I saw:
- No "error sending packet Os { code: 65, kind: HostUnreachable, message: 'No route to host' }" errors on my end
- Just the normal `libmdns DEBUG libmdns::fsm] received question` messages for discovery queries (_spotify-connect._tcp.local, etc.)
- Everything authenticated and shut down cleanly

So yeah, looks like those warnings are probably specific to certain network setups, as @photovoltex suggested. I couldn't reproduce them here, but thought I'd share just in case it helps!

**Comment by michaelherger** [comment]
Thanks - I'll see whether I can find something. I'm using PiHole - maybe it's swelling a little too much.

**Comment by michaelherger** [comment]
Left it running over night - around 8h of continuous playback.

File: core/src/spclient.rs [hunk 2]
```diff
@@ -572,39 +570,67 @@ impl SpClient {
...
-            None,
-            None,
-            &SPCLIENT_FALLBACK_ENDPOINT,
-        )
-        .await
+    pub async fn get_extended_metadata(
+        &self,
+        request: BatchedEntityRequest,
+    ) -> Result<BatchedExtensionResponse, Error> {
+        let endpoint = "/extended-metadata/v0/extended-metadata";
```
Comment (roderickvd) [inline core/src/spclient.rs]: Nitpick: could be `const` (though compiler will probably do that already).

**Review by roderickvd — DISMISSED** [review]
Looks good to me with a minor nitpick.
Can't remember why I suggested that builder pattern here, so probably forget about it.

File: core/src/spclient.rs (hunk 1 above)
Comment (roderickvd) [reply core/src/spclient.rs:596]: Can't remember why so best to forget about that.

**Comment by pienczyk** [comment]
I just built it for my Raspberry and it works. Thanks @photovoltex and @roderickvd !

File: core/src/spclient.rs (hunk 2 above)
Comment (photovoltex) [reply core/src/spclient.rs]: Seems fair enough. I just did inline it here and replace other parts where this could be const. Not necessary but doesn't hurt.

**Comment by Masterolic** [comment]
I would really appreciate if someone could implement extended metadata on python version https://github.com/kokarare1212/librespot-python/issues/321

I know this is librespot rust and not the place for it but  librespot doesn't have python version so kindly someone:)

**Comment by EduardLupu** [comment]
Thanks! I wonder why they removed the preview from https://spclient.wg.spotify.com/metadata/4/track/, it broke my app. Will use this solution!
