### PR TITLE
Dealer: Improve disconnect

### LINKED ISSUE #1419: Playlist playback stopped after a few hours with a broken pipe (os error 32) error / non recoverable websocket/TLS error (using Dealer)
### Description
Playlist playback stopped after a few hours with a broken pipe (os error 32) error
Let me know if more diagnostics can help.

### Version
72b6ad939790fffa9b1e4fe364fb2444d14ac34a (post #1356 Dealer merge)

### How to reproduce
Steps to reproduce the behavior in *librespot* e.g.
1. Launch `librespot` with librespot -c ~/.cache/librespot --cache-size-limit 64G -n "Pi Zero" -b 320  --device hw:CARD=Set,DEV=0 --device-type avr --backend alsa 
2. Start playlist - this time was using the web client but not sure it has any impact
3. Wait a few hours
4. Playback stops. Notice non recoverable websocket/TLS error in togs

### Log

> [2024-12-14T17:26:28Z INFO  librespot_playback::player] Loading <Pieteron> with Spotify URI <spotify:track:2hT7SV5QUhbO0p8T1dkHS6>
> [2024-12-14T17:26:29Z INFO  librespot_playback::player] <Pieteron> (202000 ms) loaded
> [2024-12-14T17:29:50Z INFO  librespot_playback::player] Loading <Porsche 944> with Spotify URI <spotify:track:6JSkc4vPxHuTqgSuJ2vMu9>
> [2024-12-14T17:29:51Z INFO  librespot_playback::player] <Porsche 944> (235795 ms) loaded
> [2024-12-14T17:33:29Z ERROR librespot_core::session] Connection to server closed.
> [2024-12-14T17:33:46Z INFO  librespot_playback::player] Loading <El camino negro> with Spotify URI <spotify:track:46TKHBSVXIOYjfi3pp6X7F>
> [2024-12-14T17:33:46Z ERROR librespot_core::session] Broken pipe (os error 32)
> [2024-12-14T17:33:46Z WARN  librespot_core::dealer] Websocket connection failed: IO error: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof
> [2024-12-14T17:33:46Z WARN  librespot] Spirc shut down unexpectedly
> [2024-12-14T17:33:47Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:4070"
> [2024-12-14T17:33:47Z INFO  librespot_core::session] Authenticated as '****' !
> [2024-12-14T17:33:47Z INFO  librespot_core::session] Country: "FR"
> [2024-12-14T17:33:47Z INFO  librespot_core::spclient] Resolved "gew1-spclient.spotify.com:443" as spclient access point
> [2024-12-14T17:33:47Z INFO  librespot_connect::spirc] active device is <> with session <e8916f214441c5cd46d01b0af14e3d80>
> [2024-12-14T17:33:48Z ERROR librespot_core::audio_key] Audio key response timeout
> [2024-12-14T17:33:48Z WARN  librespot_playback::player] Unable to load key, continuing without decryption: Operation aborted { audio key response timeout }
> [2024-12-14T17:33:52Z ERROR librespot_audio::fetch::receive] Streamer error requesting range 6356992 +65536: Error { kind: Unknown, error: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }
> [2024-12-14T17:34:00Z ERROR librespot_playback::player] Unable to read audio file: Symphonia Decoder Error: Deadline expired before operation could complete { wait timeout exceeded }
> unavailable
> [2024-12-14T17:34:06Z WARN  librespot_core::dealer] No subscriber for msg.uri: hm://collection/collection/antoinecellerier
> [2024-12-14T17:34:06Z WARN  librespot_core::dealer] failure during data parsing for hm://collection/collection/antoinecellerier/json: Invalid state { base64 decoding failed: Invalid symbol 123, offset 0. }
> end_of_track

### Host (what you are running `librespot` on):
- OS: Linux pizero 6.6.51+rpt-rpi-v8 # 1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
- Platform: Raspberry Pi Zero 2 W Rev 1.0

### PR DESCRIPTION
**Pull request by photovoltex**
Disconnecting now only handles disconnecting and not pausing/stopping. But because it feels unnatural to call disconnect on the `Spirc` and not having the player pause, the method now provides an additional option to explicitly pause.

improves the behavior in #1419 but doesn't fix it

### CODE REVIEW

**Comment by roderickvd** [comment]
I agree, it makes sense to have that argument.

**Review by roderickvd — DISMISSED** [review]

File: connect/src/spirc.rs [hunk 1]
```diff
@@ -438,20 +438,15 @@ impl SpircTask {
...
                     }
                 },
-                else => break
-            }
-        }
-
-        if !self.shutdown && self.connect_state.is_active() {
-            if let Err(why) = self.notify().await {
-                warn!("notify before unexpected shutdown couldn't be send: {why}")
+                else => {
```
Comment (photovoltex) [inline connect/src/spirc.rs:441]: Btw. I think this is not completly correct. I think i had a wrong idea how this part works, but the disconnect still has to occure outside. Otherwise branches can stil break and by that skip the disconnect here.

Comment (photovoltex) [reply connect/src/spirc.rs:441]: The general code flow didn't change with the dealer implementation (and this here is the `tokio::select!` main loop in the `SpircTask::run` method that existed before :D). Just the underlying logic changed pretty drastically, but thats because the dealer handles informations and the queue quite different.

Anyhow, thanks for the hint! I will look into it later. Didn't even know of `ControlFlow` yet.

**Review by roderickvd — APPROVED** [review]
LGTM

**Comment by photovoltex** [comment]
_@roderickvd do you want to merge it or should I do it myself?_
